### ISSUE TITLE
I am not able to generate crds from current master

### ISSUE THREAD

**Issue by smiklosovic** [pravega/zookeeper-operator#114]
I am getting this:

```
[smiklosovic@E091-FED zookeeper-operator]$ operator-sdk generate openapi --verbose
DEBU[0000] Debug logging is set                         
INFO[0000] Running OpenAPI code-generation for Custom Resource group versions: [zookeeper:[v1beta1], ] 
ERROR: logging before flag.Parse: E0108 22:07:22.026506   28940 openapi.go:365] Error when generating: TypeMeta, TypeMeta invalid type
Error: openapi-gen generator error: Failed executing generator: some packages had errors:
cannot generate spec for type invalid type

Usage:
  operator-sdk generate openapi [flags]

Flags:
  -h, --help   help for openapi

Global Flags:
      --verbose   Enable verbose logging

[smiklosovic@E091-FED zookeeper-operator]$ operator-sdk version
operator-sdk version: v0.10.0-dirty, commit: ff80b17737a6a0aade663e4827e8af3ab5a21170

```

I am not sure I am getting that right but are not crds in deploy obsolete? Where are all the fields in these specs?

**Comment by pbelgundi** [comment]
@smiklosovic  Note that in CRDs with apiVersion v1beta1 specification of structural schema is optional and not mandatory:
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema
Hence in the crd.yaml specified in the deploy folder, we only specify the mandatory fields like apiversion, kind, metadata and some additional information. The zookeeper "spec" is fleshed out by the operator using constructs in the types file.

**Comment by anishakj** [comment]
Closing this issue, as the query is answered. Please feel free to reopen in case of any further queries.
