### ISSUE TITLE
Hardcoded cluster domain name

### ISSUE THREAD

**Issue by okhotnikov-aa** [pravega/zookeeper-operator#118]
Hi,
cluster domain name hardcoded as cluster.local
`func headlessDomain(z *v1beta1.ZookeeperCluster) string {
	return fmt.Sprintf("%s.%s.svc.cluster.local", headlessSvcName(z), z.GetNamespace())
}`
,so you cant resolve names of pods, if your cluster domain name is different.

Actually, looks like svc and cluster domain section may be not neccessary, because pods can resolve names using only service.namespace.

**Comment by mp-007** [comment]
What is the staus here ?

Overwriting domainName should fix the problem ?

`return fmt.Sprintf("%s.%s.svc.%s", headlessSvcName(z), z.GetNamespace(), z.Spec.DomainName)`

**Comment by anishakj** [comment]
Fixed with PR https://github.com/pravega/zookeeper-operator/pull/200
