### ISSUE TITLE
Pod Management Policy

### ISSUE THREAD

**Issue by AdheipSingh** [pravega/zookeeper-operator#121]
https://github.com/pravega/zookeeper-operator/blob/007fc48abcfb6d1fcf2c5b0d892caf577d15322b/pkg/zk/generators.go#L64

Any specific reason for  hardcoding  OrderedReady. I was planning to implement parallel as pod management policy, as i am running combined scripts which shall launch zookeeper+druid stack in a go.

**Comment by pbelgundi** [comment]
@AdheipSingh Its a lot easier to bring up the cluster **correctly** with _OrderedPodManagement_ Zookeeper requires that not more than 1 joining server in the initial configuration should be a 'participant' else it could lead to a split brain situation :

See "Warning" in this section of Zookeeper documentation:
https://zookeeper.apache.org/doc/r3.5.5/zookeeperReconfig.html#ch_reconfig_dyn

Would like to understand why you were considering using "ParallelPodManagement" ?

**Comment by fpj** [comment]
@AdheipSingh I'm closing this issue for now, please feel free to reopen it if you have further comments or questions.
