### ISSUE TITLE
ZK Operator should be able to watch a configurable set of namespaces

### ISSUE THREAD

**Issue by amuraru** [pravega/zookeeper-operator#142]
Controller-runtime added support in newer version to configure controllers to watch a certain set of namespaces.
As it is now the operator can be configured to `watch` either _ALL_ or a single _Namespace_
In environments where multiple instances of ZK clusters are required, having a single operator overseeing multiple instances across many NS, simplifies the deployment.

**Comment by amuraru** [comment]
I have a working version on my fork and happy to submit a PR here, but it depends on https://github.com/pravega/zookeeper-operator/pull/99 so we need that first in.

**Comment by jdmaguire** [comment]
There's a way to get it to watch _ALL_ namespaces? Is that just through deploying the operator bare or is there a way to kick the chart to do it?

**Comment by jdmaguire** [comment]
Sorry for that 😅 Hit `Close` by mistake. I'm used to `Cancel` being there.

**Comment by amuraru** [comment]
This issue requires https://github.com/pravega/zookeeper-operator/pull/156

**Comment by amuraru** [comment]
Filed #201 to fix this
