### ISSUE TITLE
Create PR validation tasks in GithubActions

### ISSUE THREAD

**Issue by spiegela** [pravega/zookeeper-operator#148]
PR validation tasks required:
- unit tests passed
- Go lint checking via `golangci-lint`
- Code quality and coverage should have positive change

Perhaps e2e tests should not be included in PR validation, and instead within release validation, but I'm open to discussion on this topic.  I'm also flexible on what code quality and coverage reporting we'd like to use, but I'm a fan of both [Codacy](codacy.com) and [Code Climate](codeclimate.com).

TODO
- [x] Add DCO check
- [x] Add Codecov checks
- [x] Make DCO, build, and Codecov checks required
- [ ] Configure Codecov

**Comment by pbelgundi** [comment]
@spiegela What does the scope of this issue cover other than E2E tests?

**Comment by derekm** [comment]
Added DCO check, and made DCO & build checks required.

**Comment by derekm** [comment]
Added Codecov checks and made them required.

Default Codecov thresholds can be change committing a `.codecov.yml` config file to the root of this repo. Cf., https://github.com/pravega/pravega/blob/master/.codecov.yml
