### ISSUE TITLE
Support zookeeper-exporter/jmx-exporter 

### ISSUE THREAD

**Issue by whitleykeith** [pravega/zookeeper-operator#155]
I'd like the operator to either

(1) surface a field in the `Pod` field to add containers that can be used to surface metrics
or 
(2) surface them up first class by adding those containers by default to the zk pods.

**Comment by pbelgundi** [comment]
@whitleykeith Could you please provide some more details about what you need.

**Comment by AljoschaP** [comment]
It would be awesome if the operator would support the [prometheus jmx_exporter](https://github.com/prometheus/jmx_exporter). For example, the [Banzaicloud Kafka-Operator](https://github.com/banzaicloud/kafka-operator) exposes the metrics of the Kafka broker and Cruise Control by default using the jmx_exporter.

**Comment by e11it** [comment]
Just to notice.
Zookeeper since 3.6.0 is able to expose prometheus metrics out of the box.

https://zookeeper.apache.org/doc/r3.6.0/zookeeperAdmin.html#sc_monitoring
```
Since 3.6.0 ZooKeeper binary package bundles an integration with Prometheus.io

metricsProvider.className : Set to "org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider" to enable Prometheus.io exporter.
metricsProvider.httpPort : Prometheus.io exporter will start a Jetty server and bind to this port, it default to 7000. Prometheus end point will be http://hostname:httPort/metrics.
metricsProvider.exportJvmInfo : If this property is set to true Prometheus.io will export useful metrics about the JVM. The default is true.
```

**Comment by pbelgundi** [comment]
Instead of adding custom code for "zookeeper-exporter/jmx-exporter" it may be better to just move to zk latest version.

**Comment by whitleykeith** [comment]
I think upgrading to the latest ZK would meet our needs.

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/175
