### ISSUE TITLE
Helm chart lacks namespace fields on namespace scoped resources

### ISSUE THREAD

**Issue by baluchicken** [pravega/zookeeper-operator#161]
#### Problem description:
Helm chart lacks namespace filed on namespace scoped resources
#### Suggestion for improvement: 
Please improve helm chart with
```namespace: {{ .Release.Namespace }}``` on namespace scoped resources.

**Comment by bourgeoisor** [comment]
`namespace: {{ .Release.Namespace }}` is redundant, here.

Implicitly, if not specifying a `metadata.namespace` on a resource, then `{{ .Release.Namespace }}` is the default that Helm uses.

This is not a bug in functionality, rather it could indeed potentially improve legibility for Helm users that does not know that fact, though.

**Comment by amuraru** [comment]
That applies to helm install/upgrade afaik not to helm template which generates raw k8s yaml files some tools/users are using to apply via other CD tools.

**Comment by SrishT** [comment]
@amuraru these charts are meant to be used for installation via helm only. If you need yaml files for deploying zookeeper using any other tool, the manifest files provided [here](https://github.com/pravega/zookeeper-operator/tree/master/deploy) should be used.

**Comment by bourgeoisor** [comment]
Ok I see what you mean (e.g. not necessary using `helm install` but still using `helm template` to generate the manifests.)

I was under the impression that `helm template --namespace <namespace>` would just do the trick, but it doesn't seem to be the case.

Adding `namespace: {{ .Release.Namespace }}` is a good improvement for this.
