### ISSUE TITLE
Allow a different reference to image in the ZK yaml for Helm

### ISSUE THREAD

**Issue by ryphon** [pravega/zookeeper-operator#162]
I'm working with Helm and a Jenkins pipeline with some devs that are quite time restrictive.
Our K8s pipeline as is looks for a list of the images to pull and cache so that it doesn't have to do a docker pull for every single environment.  This may be an edge case I should get covered in the pipeline, but for consistency, it seems as if the zookeeper template should be adjusted.

So we end up with a situation where I get this, `Found what appears to be an invalid image name. It will be skipped: ['repository':'private-docker-repo.xyz/zookeeper', 'tag':'latest']` because it's trying to  reconcile the `image: repository: private-docker-repo.xyz tag: latest` as an image to parse, but it's getting a list.

Other helm charts, including the zookeeper-operator, use the ```image: 'private-docker-repo.xyz/zookeeper-operator:latest'``` as one line in the yaml file.

For consistencies sake, I'd like the zk cluster to handle this natively. My current solution is to use the exporter, take the compiled resources and build them into helm chart templates, but seems that I should probably be doing this directly in the crd definition as it gets deployed.

**Comment by ryphon** [comment]
Specifically, it's running helm template and looking for the `image` key and parsing out the value as a string for the docker image to pull.

**Comment by ryphon** [comment]
However, I am seeing that this line... `https://github.com/pravega/zookeeper-operator/blob/6fd02160fbf6a99b515053af47c5958814c23c08/pkg/zk/generators.go#L91` doesn't seem to do what I feel like it's doing..

If I set the image: tag in the yaml to a string, it doesn't seem to properly create the resources as required.

**Comment by ryphon** [comment]
Ah, now I've found `https://github.com/pravega/zookeeper-operator/blob/d84aefddaeb3b457b8478b637406d225330ef38c/pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go#L228` to be where the repository/tag is created via the list in yaml...

Is this something I should just change locally and build the container for my own use case, or do my thoughts about consistency have merit to the overall project?

**Comment by spiegela** [comment]
@ryphon the use of a map for the `image` is quite common across Helm chart repositories.  For examples, take a look at Helm charts in the [stable Kubernetes repo](https://github.com/helm/charts/blob/master/stable). I spot-checked several to make sure I wasn't off-base, and they all use the same format as our own. The [image value for zookeeper-operator](https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/values.yaml#L5-L8) also uses this same pattern.

My first recommendation is that the pipeline be updated to handle a map repsonse with `image.repository` and `image.tag`.  If this is not possible, and your team requires that the `image` value in the Helm chart be a single string value, then I recommend creating a separate chart in your own repository.  It can still reference the same containers as our charts, but with your own requirements for the format of the `values.yml` file.

I would recommend this approach over using the exporter, since the operator provides additional run-time support that the exporter cannot.

**Comment by ryphon** [comment]
@spiegela It ends up coming down to the final helm template. The zk `helm template` ends up having the image.repo and image.tag. The zk-op `helm template` ends up with just image and it's the full image+tag. There are some pipeline changes coming that'll let me hand define images, so I'll just tell the pipeline what the zk image should be, and it should be fine I think.

**Comment by ryphon** [comment]
ZK Op Template:
```apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-zookeeper-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: RELEASE-NAME-zookeeper-operator
  template:
    metadata:
      labels:
        name: RELEASE-NAME-zookeeper-operator
        component: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
      - name: RELEASE-NAME-zookeeper-operator
        image: "private-docker-repo.xyz/zookeeper-operator:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6000
          name: metrics
        command:
        - zookeeper-operator
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: RELEASE-NAME-zookeeper-operator
```
ZK Template:
```
# Source: zookeeper/templates/zookeeper.yaml
apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: RELEASE-NAME-zookeeper
spec:
  replicas: 3
  image:
    repository: private-docker-repo.xyz/zookeeper
    tag: latest

  persistence:
    volumeReclaimPolicy: Retain
    spec: 
      storageClassName: 
      resources:
        requests:
          storage: 10Gi
```

**Comment by anishakj** [comment]
@ryphon  Is this still an issue?

**Comment by ryphon** [comment]
Nah, I just should have closed it, my mistake. Theoretically it is, but the pipeline added functionality to define containers regardless of what `helm template` gives.
