### ISSUE TITLE
Please update to zk 3.5.7 or 3.6.0

### ISSUE THREAD

**Issue by AceHack** [pravega/zookeeper-operator#164]
There are so many bug fixes please update

**Comment by amuraru** [comment]
Issues #128 and #155 also require upgrade to zk 3.6

zk 3.6.1 is at this time in rc mode and due next week.
I suggest operator upgrades to 3.6.1 directly as that fixes a couple of issues in 3.6.0

**Comment by AceHack** [comment]
Yes I would be happy for 3.6.1 next week.

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/175
