### ISSUE TITLE
Can we add annotations for the pvc created?

### ISSUE THREAD

**Issue by snkshukla** [pravega/zookeeper-operator#165]
I know we can pass the `storageClassName` in the `pvc` spec and we are using that right now. But **is it possible** to pass the annotations for the `pvc` template?

It would be really helpful if we could do that as we use portworx for our pvc and we need to add some annotations for it to work, specifically these annotations are storage class and the secret name used for encryption.

If this is not supported, I'd be happy to help in adding this if someone can point me in the right direction.

**Comment by SrishT** [comment]
@snkshukla this functionality is currently not supported. So either you can go ahead and add it or we can take it up in our next cycle.

**Comment by fpj** [comment]
> If this is not supported, I'd be happy to help in adding this if someone can point me in the right direction.

hey @snkshukla , we would really appreciate if you could contribute.
