### ISSUE TITLE
Deepcopy for updates

### ISSUE THREAD

**Issue by AdheipSingh** [pravega/zookeeper-operator#166]
https://github.com/pravega/zookeeper-operator/blob/master/pkg/zk/synchronizers.go#L19

I see no deepcopy objects being used. Can we use deepcopy here ?

**Comment by Prabhaker24** [comment]
By Deep copy object here do you mean doing a deep copy of next sts spec to current sts spec, we don't do it as here we don't want all the fields inside spec to get copied we only want the replica count, update strategy and template field of the current sts spec to be changed. 
You can refer to  https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#statefulset-v1-apps  it shows all the field that a stateful set spec contains.
 one more thing is doing a deep copy at this moment might work and not cause any problem but we would end up copying more fields then what is intended so maybe in the future it might break something if we do a code change in the way we are creating our statefulset which you can refer https://github.com/pravega/zookeeper-operator/blob/master/pkg/zk/generators.go#L42

**Comment by Prabhaker24** [comment]
closing this issue as the issuer hasn't replied back.

**Comment by AdheipSingh** [comment]
apologies for the delay, totally missed it. We dont need to copy the whole object i agree with you on the context.
```
// SyncStatefulSet synchronizes any updates to the stateful-set
// Use Deepcopy funcs
func SyncStatefulSet(curr *appsv1.StatefulSet, next *appsv1.StatefulSet) {
	currSts := curr.DeepCopy()
	currSts.Spec.Replicas = next.Spec.Replicas
	currSts.Spec.Template = next.Spec.Template
	currSts.Spec.UpdateStrategy = next.Spec.UpdateStrategy

}
```

**Comment by Prabhaker24** [comment]
There is some misunderstanding so here **next** is just a place holder that is created with the(changed specs) and we are just modifying the **current sts** to the changed values and leaving things on k8 to match the status to the spec(for example lets say the user has modified the Replica count to 6 from 3 then, in that case, next.Spec.Replicas will be 6 and when **SyncStatefulSet()** is called curr.Spec.Replicas will become 6 and then k8 will bring 3 new pods as curr.Spec.Replicas will not be equal to curr.Status.ReadyReplicas ). please refer to the code here https://github.com/pravega/zookeeper-operator/blob/45f8a92e7db437409893372a5d52542f2e4c2d8d/pkg/controller/zookeepercluster/zookeepercluster_controller.go#L227 to understand how we are using it. In the example that you have shown you are creating a new sts altogether there is no point in changing values in that as we want values in our original sts to be changed.
