### ISSUE TITLE
Fix Travis configuration so Travis jobs can be executed on forks

### ISSUE THREAD

**Issue by pbelgundi** [pravega/zookeeper-operator#181]
## Description
Currently Travis jobs cannot run on a fork branch since certain environment variables defined in Travis settings are not available on the fork branch.
Need to figure out a way around this, so Travis builds can be executed on fork branches.
We need to define `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` as env variables in travis settings, if we are planning to create clusters in aws environment. Also `DOCKER_TEST_USER` and `DOCKER_TEST_PASS` is required to push the images to docker hub.

Currently, Travis is not allowing encrypted variables to be exported on  forked repo due to security reasons.(https://github.com/travis-ci/travis-ci/issues/6611)

**Comment by fpj** [comment]
Are you talking about the credentials?

**Comment by anishakj** [comment]
> Are you talking about the credentials?

We are setting AWS credentials in travis  settings, that is required to create the cluster. Also docker login/passwd are mentioned  there. These wont be available if we run the tests on a forked branch.

**Comment by fpj** [comment]
I got it, but what are the variables mentioned in the description and why are they not part of the forker branches? The description is not very precise.

**Comment by pbelgundi** [comment]
@anishakj Could you please explain why this does not work.

**Comment by anishakj** [comment]
> @anishakj Could you please explain why this does not work.

updated the description

**Comment by pbelgundi** [comment]
@anishakj I see environment variables defined in the pravega/pravega repository as well and there we're able to run Travis builds on Forks. What is different about this repository?

**Comment by anishakj** [comment]
> @anishakj I see environment variables defined in the pravega/pravega repository as well and there we're able to run Travis builds on Forks. What is different about this repository?

I have checked pravega travis job, none of the ENV variables are used in tests

**Comment by anishakj** [comment]
I have seen that other projects also have the same issue. They have to  copy the changes to a branch from the repo directly and run the tests. (https://github.com/OHDSI/Achilles/issues/165)

**Comment by Prabhaker24** [comment]
Fixed with this pr https://github.com/pravega/zookeeper-operator/pull/211
