### ISSUE TITLE
Publish the helm charts to a public repository

### ISSUE THREAD

**Issue by SrishT** [pravega/zookeeper-operator#190]
### Description
The charts need to be published externally in a public repository (like helm hub).

### Importance
must have

### Location
zookeeper helm charts

**Comment by dalbani** [comment]
Hi, do you think you could publish the Helm chart to a public repository? Thanks!

**Comment by SrishT** [comment]
@dalbani the `0.2.8` zookeeper charts have been published to https://charts.pravega.io
Publishing them to Helm Hub is also on our roadmap.

**Comment by dalbani** [comment]
Thanks for your quick respnse, @SrishT!
Nice to hear that the chart is available on https://charts.pravega.io/.
I had not seen it mentioned anywhere.

**Comment by SrishT** [comment]
@dalbani we plan to update the documentation once it has been tested end to end.

**Comment by SrishT** [comment]
From version 0.2.8 onwards, zookeeper charts for the released zookeeper versions will be available in https://charts.pravega.io. The charts for version 0.2.8 are already available here.
Even the documentation has now been updated to reflect the same.
