### ISSUE TITLE
Fix envoy detection in zooKeeperStart script

### ISSUE THREAD

**Issue by 2phost** [pravega/zookeeper-operator#193]
Issue created to do a pull request.

The block code that detects and waits for the Envoy does not work because of the ```set -e``` line.
The line ```SC=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:15000/ready)``` fails and the script stops running.

I fixed that by disable the flag in this block of code.

**Comment by 2phost** [comment]
Related to #194

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/194
