### ISSUE TITLE
Handle scale-up/scale-down operations

### ISSUE THREAD

**Issue by spiegela** [pravega/zookeeper-operator#2]
Depends upon #4. There may be other requirements to handle scale-up and down using `kubectl scale`. However, the cluster _can_ be scaled by changing the cluster spec and re-applying wtih `kubectl apply`.

**Comment by fpj** [comment]
@spiegela one clarification: why is `kubectl edit` not supposed to work?

**Comment by fpj** [comment]
Actually, to elaborate on the point, I have tried to increase the ensemble size from 3 to 5, and I get to see that the desired number is 5 and current is 4, but the fourth pod is actually pending (forever). It will require a bit if debugging to understand what's happening with that server.

**Comment by fpj** [comment]
Test

**Comment by spiegela** [comment]
@fpj  I think that the `kubectl edit ...` method of scaling the zookeeper cluster _should_ work. Take a look at the pod that is currently pending with `kubectl describe pod ...` and we may see why it isn't starting. It could be that the affinity/anti-affinity rules are preventing it from starting.

**Comment by chaicesan** [comment]
> Depends upon #4. There may be other requirements to handle scale-up and down using `kubectl scale`. However, the cluster _can_ be scaled by changing the cluster spec and re-applying wtih `kubectl apply`.

When I update the cluster spec and run `kubectl apply -f path/to/spec.yml` I see no change in the number of pods/desired replicas. I try to scale up from 3 to 5 and I have enough nodes on GKE. What is going on?

**Comment by anishakj** [comment]
We are able to do scaling via zookeeper-operator. So closing this issue
