### ISSUE TITLE
Clarify difference between KubernetesClusterDomain and DomainName

### ISSUE THREAD

**Issue by lukemassa** [pravega/zookeeper-operator#208]
### Description

I recognize first of all this is a problem entirely of my own creation. When adding https://github.com/pravega/zookeeper-operator/pull/200 I created the notion of KubernetesClusterDomain (i.e. defaulting to cluster.local, but overideable, corresponding to https://github.com/kubernetes/dns/blob/master/cmd/kube-dns/app/options/options.go#L57, described here: https://kubernetes.io/docs/tasks/administer-cluster/dns-custom-nameservers/#introduction).

However, there also exists a setting `DomainName` (https://github.com/pravega/zookeeper-operator/blob/master/pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go#L76), whose only purpose seems to be setting the `external-dns.alpha.kubernetes.io/hostname` on the Service (described here: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/faq.md).

My question is whether we should have related the two at all? If the idea is that `DomainName` is how this service is addressed from outside the cluster, completely out of the control of the operator, whereas KubernetesClusterDomain helps build the internal DNS name, maybe we should change the name of the former to `ExternalHostName` and add a few lines in the comments around the setting to clarify their different usage?

Even if it's decided it's not worth changing the variable name, given that my understanding is correct I'd be happy to write up the comments to clarify the role of the settings.

### Importance

Minimal, documentation/clarification.

### Location

`pkg/apis/zookeeper/v1beta1/zookeepercluster_types.go`

### Suggestions for an improvement

Given that my understanding above is correct, comments to clarify the roles and/or changing the variable name to make it clear it's external.

If my understanding is wrong, and these values are related somehow, my suggestion would be one of them be derivable from the other.

**Comment by anishakj** [comment]
@lukemassa  your understanding is correct. DomainName in the spec is used for setting the annotations.

**Comment by anishakj** [comment]
We wont be able to change the spec parameter as it can cause compatibility  issues while doing upgrade.

**Comment by Prabhaker24** [comment]
I have raised a pr and have changed the description of the DomainName field to reflect what it does we can't change the field now as @anishakj  has rightly pointed out that it will cause compatibility issues during our operator upgrades.

**Comment by Prabhaker24** [comment]
closing this issue as the pr https://github.com/pravega/zookeeper-operator/pull/234 is merged.
