### ISSUE TITLE
zoo.cfg updated parameters are not picked up during rolling restarts

### ISSUE THREAD

**Issue by amuraru** [pravega/zookeeper-operator#222]
### Description

Updating ZK parameters like `initLimit`, `tickTime` are not reflected in ZK when the cluster is restarted. 
Steps to reproduce:
- deploy a new ZK cluster 
- update `initLimit` in ZK spec
- rolling restart is triggered and one would expect the new value to be reflected in zk runtime
This is not happing and `/data/conf/zoo.cfg` configuration file used in zk command line does not reflect the change.

https://github.com/adobe/zookeeper-operator/blob/dede2bacf9ff56fa85bd81286cea0fd20815e632/pkg/zk/generators.go#L203-L217

#### Analysis

Following the param change it seems the `/conf/zoo.cfg` correctly picks up the change but the actual `/data/conf/zoo.cfg` is only copied once during initial installation (and never updated)
https://github.com/adobe/zookeeper-operator/blob/master/docker/bin/zookeeperStart.sh#L140-L143

### Importance
must-have

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_

**Comment by anishakj** [comment]
I have tried it and observed that the change of spec parameters are reflected in zookeeper configmap.

**Comment by amuraru** [comment]
Correct but that configmap is not what the zk is using in the running pod

**Comment by anishakj** [comment]
Yes , you are correct. We will work on the fix
