### ISSUE TITLE
Support multi images

### ISSUE THREAD

**Issue by qixiaogang** [pravega/zookeeper-operator#228]
### Description

I wan to deploy a sidecar with the zookeeper instance to do some monitoring of the zookeeper instance.

### Suggestions for an improvement

Do you have a plan to support multi images?
Thanks

**Comment by Prabhaker24** [comment]
we have support for istio from 0.2.8 you can used itfor monitoring the zookeeper instance

**Comment by qixiaogang** [comment]
@Prabhaker24  Do you have a plan to support configuring multi images in the crds? I want to deploy a sidecar with the zookeeper and put some logics in the sidecar

**Comment by Prabhaker24** [comment]
@qixiaogang, Sorry I don't properly understand what you mean by configuring multi images in the crds, In my understanding, you can deploy Istio with the zookeeper cluster and use it for your purpose.

**Comment by qixiaogang** [comment]
@Prabhaker24  I file a PR to support multi images in https://github.com/pravega/zookeeper-operator/pull/230. 
The purpose of this PR is to allow use to customize container's images deploy with zookeeper container.

**Comment by anishakj** [comment]
Fixed by PR #230
