### ISSUE TITLE
 "system:serviceaccount:zk:zookeeper-operator" cannot list resource "zookeeperclusters" in API group "zookeeper.pravega.io" at the cluster scope [root@ip-10-20-30-193 zookeeper-operator]# 

### ISSUE THREAD

**Issue by DevOpserzhao** [pravega/zookeeper-operator#236]
### Description

_(Describe the feature, bug, question, proposal that you are requesting)_

### Importance

_(Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have))_

### Location

_(Where is the piece of code, package, or document affected by this issue?)_

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_

**Comment by anishakj** [comment]
Could you please elaborate more on this issue? What are the operations performed to hit this issue

**Comment by anishakj** [comment]
We are seeing cluster roles are present, please see here https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/templates/clusterrole.yaml#L10-15

**Comment by anishakj** [comment]
Closing this issue as it looks invalid. Please feel free to reopen if you see any issues again
