### ISSUE TITLE
Can't get the operator to watch more than 1 specific namespace

### ISSUE THREAD

**Issue by dalbani** [pravega/zookeeper-operator#238]
### Description

I don't know what I'm doing wrong, but I haven't been able to get the operator to watch more than 1 specific namespace.
So what I mean is: all namespaces, yes. A single specific namespace, yes as well.
But a list of (comma-separated) namespaces, no, the operator just doesn't pick up any of them.
I use the `watchNamespace` parameter to the Helm chart by the way.
I know that MR #201 is supposed to have implemented such a feature, but I can't get it to work.
Has anyone some experience with this functionality?

### Importance

Must-have.

**Comment by dalbani** [comment]
@anishakj May I ask you how you tested the functionality back in https://github.com/pravega/zookeeper-operator/pull/201#issuecomment-648093152?

**Comment by dalbani** [comment]
@amuraru Would you have a test case as well? Thanks.

**Comment by anishakj** [comment]
@dalbani  Can u mention the operator version of operator. Fix has gone in `0.2.9-rc0`

**Comment by dalbani** [comment]
@anishakj Oh, silly me, yes that was it 🤦. I hadn't updated the image version to `0.2.9-rc0`. It works now, thanks.
By the way, speaking of versions, do you plan releasing a `0.2.9-rc0` version of the Helm chart as well (on _charts.pravega.io_)?
There has been important changes since `0.2.8` (for example the ability to use `--skip-crds`).
For now I have pushed a "fork" to my local chart repository. So it's not absolutely blocking to me.

**Comment by anishakj** [comment]
We will be publishing the charts once 0.2.9  stable version is released.

**Comment by amuraru** [comment]
@anishakj agree - we should add a test case for multi ns watch

**Comment by anishakj** [comment]
@amuraru  In operator-sdk, currently there is no provision to watch multiple name spaces and our end to end tests are based on that. In our manual testing we can include this test case.

**Comment by anishakj** [comment]
Closing this issue as the fix is available in `0.2.9-rc0`
