### ISSUE TITLE
kubernetesClusterDomain is not taking effect

### ISSUE THREAD

**Issue by EladDolev** [pravega/zookeeper-operator#239]
### Description

whether setting `kubernetesClusterDomain` or not it will always stay cluster.local
when looking at the ZookeeperCluster object, the `kubernetesClusterDomain` is not there, and even when patching the object and adding it, it still doesn't have any effect

### Importance

can't deploy this in my cluster that uses a non-default clusterDomain

**Comment by anishakj** [comment]
The fix has gone in `0.2.9.rc0` release. Are you using that version?

**Comment by EladDolev** [comment]
I wasn't.
I can confirm it is working in `0.2.9-rc0`
Thanks !!
