### ISSUE TITLE
Bootstrap Process does not handle missing DNS server correctly

### ISSUE THREAD

**Issue by maddisondavid** [pravega/zookeeper-operator#240]
### Description
Zookeeper Node bootstrap does not handle DNS not being ready and incorrectly takes a missing DNS server as meaning there are no existing ZK nodes.  This results in it incorrectly setting up a new bootstrap node and causing a "split-brain" situation on the cluster where the new node has no data from the existing ZK cluster.

### Importance
Critical as this can cause production outages when systems such as Flink attempt to recover Jobs based on information in the ZK node.

### Location
During start up of a Zookeeper node that has no existing data the `zookeeperFunctions.sh` attempts an `nslookup` and will take any error response to mean that there are no existing nodes.  However in rare node recovery type situations, the DNS servers my not be ready when the ZK POD checks and instead gets:
```
+ nslookup zookeeper-headless.edge.svc.cluster.local
;; connection timed out; no servers could be reached
```
Unfortunately `zookeeperFunctions.sh` takes this as an error condition that there are no existing nodes and bootstraps a new cluster.

### Suggestions for an improvement
It should somehow identify when `nslookup` has been successful but has no servers Vs when nslookup has failed to contact a DNS server.

**Comment by amuraru** [comment]
Is this similar to https://github.com/pravega/zookeeper-operator/pull/135 ?
