### ISSUE TITLE
pod securityContext set in the zookeeper CRD, not taking effect

### ISSUE THREAD

**Issue by priyavj08** [pravega/zookeeper-operator#244]
### Description

Tried to configure securityContext in the CRD as below and it is not taking effect
spec:
  pod: 
    securityContext:
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001

### Importance

want to have securityContext at pod level to run as nonroot user

### Location

_(Where is the piece of code, package, or document affected by this issue?)_

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_

**Comment by anishakj** [comment]
Have you changed  it in https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/values.yaml  to include securitycontext?

**Comment by priyavj08** [comment]
I directly set these in the CRD instead of coming through values.yaml

**Comment by anishakj** [comment]
No, you have to set these in values.yaml and install via helm charts

**Comment by anishakj** [comment]
> @anishakj I tried setting in values.yaml and installed through helm, still doesn't work. please let me know if there is anything I can check?
> btw, I was able to set security context for zookeeper operator pod
> 
> thanks

could you please share the details `kubectl get  zk -o yaml` details and your modified values file

**Comment by priyavj08** [comment]
here is CRD yaml

apiVersion: v1
items:
- apiVersion: zookeeper.pravega.io/v1beta1
  kind: ZookeeperCluster
  metadata:
    creationTimestamp: "2020-09-16T14:49:15Z"
    finalizers:
    - cleanUpZookeeperPVC
    generation: 2
    managedFields:
    - apiVersion: zookeeper.pravega.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          .: {}
          f:image:
            .: {}
            f:pullPolicy: {}
            f:repository: {}
            f:tag: {}
          f:persistence:
            .: {}
            f:reclaimPolicy: {}
            f:spec:
              .: {}
              f:resources:
                .: {}
                f:requests:
                  .: {}
                  f:storage: {}
              f:storageClassName: {}
          f:pod:
            .: {}
            f:resources:
              .: {}
              f:limits:
                .: {}
                f:cpu: {}
                f:memory: {}
              f:requests:
                .: {}
                f:cpu: {}
                f:memory: {}
            f:securityContext:
              .: {}
              f:runAsGroup: {}
              f:runAsNonRoot: {}
              f:runAsUser: {}
          f:size: {}
      manager: Go-http-client
      operation: Update
      time: "2020-09-16T14:49:15Z"
    - apiVersion: zookeeper.pravega.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers: {}
        f:spec:
          f:config:
            .: {}
            f:initLimit: {}
            f:syncLimit: {}
            f:tickTime: {}
          f:labels:
            .: {}
            f:app: {}
            f:release: {}
          f:persistence:
            f:spec:
              f:accessModes: {}
              f:dataSource: {}
          f:pod:
            f:affinity:
              .: {}
              f:podAntiAffinity:
                .: {}
                f:preferredDuringSchedulingIgnoredDuringExecution: {}
            f:labels:
              .: {}
              f:app: {}
              f:release: {}
            f:terminationGracePeriodSeconds: {}
          f:ports: {}
          f:replicas: {}
        f:status:
          .: {}
          f:externalClientEndpoint: {}
          f:internalClientEndpoint: {}
          f:members:
            .: {}
            f:ready: {}
            f:unready: {}
          f:readyReplicas: {}
          f:replicas: {}
      manager: zookeeper-operator
      operation: Update
      time: "2020-09-16T14:52:51Z"
    name: fed-kafka-affirmedzk
    namespace: fed-kafka
    resourceVersion: "107644"
    selfLink: /apis/zookeeper.pravega.io/v1beta1/namespaces/fed-kafka/zookeeperclusters/fed-kafka-affirmedzk
    uid: 15d5bcba-a3a4-4c6a-96ff-a485287e1698
  spec:
    config:
      initLimit: 10
      syncLimit: 2
      tickTime: 2000
    image:
      pullPolicy: IfNotPresent
      repository: cnreg-rel:5000/cna-zookeeper-zookeeper-dbg
      tag: 1.3.0-7
    labels:
      app: fed-kafka-affirmedzk
      release: fed-kafka-affirmedzk
    persistence:
      reclaimPolicy: Delete
      spec:
        accessModes:
        - ReadWriteOnce
        dataSource: null
        resources:
          requests:
            storage: 500Mi
        storageClassName: zksc
    pod:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - fed-kafka-affirmedzk
              topologyKey: kubernetes.io/hostname
            weight: 20
      labels:
        app: fed-kafka-affirmedzk
        release: fed-kafka-affirmedzk
      resources:
        limits:
          cpu: 100m
          memory: 256Mi
        requests:
          cpu: 10m
          memory: 128Mi
      securityContext:
        runAsGroup: 1001
        runAsNonRoot: true
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
    ports:
    - containerPort: 2181
      name: client
    - containerPort: 2888
      name: quorum
    - containerPort: 3888
      name: leader-election
    replicas: 3
    size: 3
  status:
    externalClientEndpoint: N/A
    internalClientEndpoint: 10.98.191.211:2181
    members:
      ready:
      - fed-kafka-affirmedzk-0
      - fed-kafka-affirmedzk-1
      unready:
      - fed-kafka-affirmedzk-2
    readyReplicas: 2
    replicas: 3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by priyavj08** [comment]
-
[crd.log](https://github.com/pravega/zookeeper-operator/files/5232980/crd.log)

attaching the yaml of zk, I see securitycontext is present here but doesn't reflect in the zookeeper cluster pods

**Comment by anishakj** [comment]
> [crd.log](https://github.com/pravega/zookeeper-operator/files/5232980/crd.log)
> 
> attaching the yaml of zk, I see securitycontext is present here but doesn't reflect in the zookeeper cluster pods

In the  output you have shared,  i am seeing securitcontext is set , can you please send the output of  `kubectl get po <zk podname> -o yaml`

**Comment by priyavj08** [comment]
[zk1.yaml.log](https://github.com/pravega/zookeeper-operator/files/5233171/zk1.yaml.log)

here it is

**Comment by priyavj08** [comment]
hi @anishakj , anything you see wrong in my config? or is this an issue? appreciate your help

thanks

**Comment by anishakj** [comment]
> hi @anishakj , anything you see wrong in my config? or is this an issue? appreciate your help
> 
> thanks

This looks like an issue. In Podspec, security context is not getting populated.

**Comment by priyavj08** [comment]
thanks @anishakj  any timeline on when this fix will be available? 

thanks

**Comment by anishakj** [comment]
Observing some permission issues to start the zookeeper pods  with non root users. Will keep posted on the findings.

**Comment by priyavj08** [comment]
@anishakj 
wondering if you have any update on this. thanks

**Comment by anishakj** [comment]
After making changes to supply security context to  pods, i am seeing below errors in zookeeper pod start up.  Still need more investigation for fixing permission issues.

```/usr/local/bin/zookeeperStart.sh: line 127: /data/zoo.cfg.dynamic: Permission denied
+ [[ false == true ]]
+ ZOOCFGDIR=/data/conf
+ export ZOOCFGDIR
+ echo Copying /conf contents to writable directory, to support Zookeeper dynamic reconfiguration
Copying /conf contents to writable directory, to support Zookeeper dynamic reconfiguration
+ [[ ! -d /data/conf ]]
+ mkdir /data/conf
mkdir: cannot create directory ‘/data/conf’: Permission denied
+ cp -f /conf/zoo.cfg /data/conf
cp: cannot create regular file '/data/conf': Permission denied
+ cp -f /conf/log4j.properties /data/conf
cp: cannot create regular file '/data/conf': Permission denied
+ cp -f /conf/log4j-quiet.properties /data/conf
cp: cannot create regular file '/data/conf': Permission denied
+ cp -f /conf/env.sh /data/conf
cp: cannot create regular file '/data/conf': Permission denied
```

**Comment by punkprzemo** [comment]
Any update on this? seems like below values which are in `kind: ZookeeperCluster` are not populated to statefulset
```
spec:
  pod:
    securityContext:
      runAsUser: 1000
      fsGroup: 1000
```

Regards

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/334
