### ISSUE TITLE
Support configure annotations for zookeeper pod

### ISSUE THREAD

**Issue by qixiaogang** [pravega/zookeeper-operator#249]
### Description

There is no way to configure the annotations of zookeeper pod

### Importance

Need to configure the annotations of zookeeper pod in our platform

### Location

Configure the annotations of .spec.pod.annotations, but check the zookeeper instance, annotations doesn't appear in the pod spec

### Suggestions for an improvement

Can we use .spec.pod.annotations to configure the zookeeper pod annotations?

**Comment by anishakj** [comment]
This is a duplicate of https://github.com/pravega/zookeeper-operator/issues/125

**Comment by qixiaogang** [comment]
@anishakj  Do you have a plan to support annotations?
Or can I file a PR to support annotations?

**Comment by anishakj** [comment]
Sure, Please go ahead

**Comment by qixiaogang** [comment]
Thanks
