### ISSUE TITLE
How to specify ZK instance log configuration

### ISSUE THREAD

**Issue by dalbani** [pravega/zookeeper-operator#252]
The ZK operator generates a `ConfigMap` containing several items:
- `zoo.cfg`
- `log4j.properties`
- `log4j-quiet.properties`
- `env.sh`

And these files get copied to the `/data/conf` directory which is used by ZooKeeper if I'm not mistaken.
I would like to configure the ZooKeeper instances to use `log4j-quiet.properties` instead of `log4j.properties`.
How can I do that? Given the fact the `ConfigMap` gets overwritten at the reconciliation phase by the way.

**Comment by anishakj** [comment]
Are you changing the log configurations at the time of fresh installation  or later?

**Comment by dalbani** [comment]
Well, I don't think it makes much of a difference AFAIK.
Because the function that creates the `ConfigMap` produces the same result when the `ConfigMap` gets created or overwritten: https://github.com/pravega/zookeeper-operator/blob/master/pkg/controller/zookeepercluster/zookeepercluster_controller.go#L447.
So I don't see how I can tweak the `ConfigMap` at any point.

**Comment by anishakj** [comment]
Yes you are correct. At the time of restart also, we are copying the log4j-quiet.proerties. https://github.com/pravega/zookeeper-operator/blob/master/docker/bin/zookeeperStart.sh#L159

**Comment by dalbani** [comment]
If only I could tell ZooKeeper to use `log4j-quiet.properties` instead of `log4j.properties`, that would be enough for me.
But I haven't been able to find a way to do it. For example via an environment variable.
Would you know another way by any chance?

**Comment by anishakj** [comment]
@dalbani  I am seeing that  it is using `log4j-quiet.properties` while starting up. https://github.com/pravega/zookeeper-operator/blob/master/docker/bin/zookeeperStart.sh#L20 Could you please explain me the difference in between `log4j.properties` and `log4j-quiet.properties`

**Comment by anishakj** [comment]
@dalbani Could you please confirm if above is the requirement

**Comment by dalbani** [comment]
@anishakj
Well, being able to provide one's own `log4j.properties` definition would probably be best, I suppose.
But being able to set the global log level is also fine for me.
Actually, I was wondering if it's not already possible via:
```yaml
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
spec:
  ...
  pod:
    ...
    env:
      - name: ZOO_LOG4J_PROP
        value: 'ERROR,CONSOLE'
```
Based on the code at https://github.com/apache/zookeeper/blob/master/bin/zkEnv.sh#L73.

(In my case, as a ZooKeeper user via the Solr operator, I'd still have to figure out how to pass this `env` information from the SolrCloud CR definition to the ZookeeperCluster CR definition. But that's another discussion.)

**Comment by anishakj** [comment]
> @anishakj
> Well, being able to provide one's own `log4j.properties` definition would probably be best, I suppose.
> But being able to set the global log level is also fine for me.
> Actually, I was wondering if it's not already possible via:
> 
> ```yaml
> apiVersion: zookeeper.pravega.io/v1beta1
> kind: ZookeeperCluster
> spec:
>   ...
>   pod:
>     ...
>     env:
>       - name: ZOO_LOG4J_PROP
>         value: 'ERROR,CONSOLE'
> ```
> 
> Based on the code at https://github.com/apache/zookeeper/blob/master/bin/zkEnv.sh#L73.
> 
> (In my case, as a ZooKeeper user via the Solr operator, I'd still have to figure out how to pass this `env` information from the SolrCloud CR definition to the ZookeeperCluster CR definition. But that's another discussion.)

We can add ENV to mention log level. But not sure if log level is mentioned via log4j-properties as well as ENV which one will take preference.  Currently we are using log4j-properties  and is hardcoded to INFO.

**Comment by anishakj** [comment]
By setting env in https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/values.yaml#L19  , logs are coming correctly for the pods according to the loge level set. Can we close this issue in that case?

**Comment by dalbani** [comment]
Yes, that's fine. Thank you.
