### ISSUE TITLE
one of the zookeeper pod is in constant CrashLoopBackOff status

### ISSUE THREAD

**Issue by priyavj08** [pravega/zookeeper-operator#259]
### Description

_(Describe the feature, bug, question, proposal that you are requesting)_
one of the pod in ZK ensemble is in crashloopbackoff state, log file shows error "cat: /data/zoo.cfg.dynamic: No such file or directory"

Bootstrap dynamic config file
+ REGISTERED=1
+ [[ 1 -eq 1 ]]
+ REGISTER_NODE=false
+ [[ false == true ]]
+ ZOOCFGDIR=/data/conf
+ export ZOOCFGDIR
+ [[ ! -d /data/conf ]]
+ [[ false == false ]]
+ [[ false == false ]]
+ echo Bootstrap dynamic config file
+ cat /data/zoo.cfg.dynamic
**cat: /data/zoo.cfg.dynamic: No such file or directory**
[maint@k8-master-70-01-dcc808-4b2c09f7b029c470 ~]$

### Importance
blocker
_(Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have))_

### Location

_(Where is the piece of code, package, or document affected by this issue?)_

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_

**Comment by priyavj08** [comment]
zookeeper container crashed with errorcode 137

**Comment by anishakj** [comment]
Could you please update the zk operator version and zookeeper version used? Also let me know which of the zookeeper pods crashed in your case?

**Comment by priyavj08** [comment]
@anishakj  I am using 0.2.4

3rd zookeeper pod keeps failing  in a cluster size of 3

**Comment by anishakj** [comment]
> @anishakj I am using 0.2.4
> 
> 3rd zookeeper pod keeps failing in a cluster size of 3
> 
> also is there is a slack channel or any other forum I can use to discuss with this community?
> 
> thanks for your help

This looks like a very old version. We have now released `0.2.9.rc2` for both operator and zookeeper. Can you try with that and update?

**Comment by priyavj08** [comment]
@anishakj  thanks, will try that.  

another issue I see,  on pod restart, Liveness and readiness probe fails.  Will these issues go away with newer release?

++ echo ruok
(UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused
+ OK=
  Warning  Unhealthy  20s (x3 over 40s)  kubelet, bhuvaneshwaran-m-tx-k8-node-1-yi6vhj-pigr5p0arj7kben1  Liveness probe failed: + source /conf/env.sh
++ DOMAIN=fed-kafka-affirmedzk-headless.fed-kafka.svc.cluster.local
++ QUORUM_PORT=2888
++ LEADER_PORT=3888
++ CLIENT_HOST=fed-kafka-affirmedzk-client
++ CLIENT_PORT=2181
++ echo ruok
++ nc 127.0.0.1 2181
(UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused
+ OK=
  Normal   Killing    20s               kubelet, bhuvaneshwaran-m-tx-k8-node-1-yi6vhj-pigr5p0arj7kben1  Container zookeeper failed liveness probe, will be restarted
  Warning  Unhealthy  1s (x3 over 21s)  kubelet, bhuvaneshwaran-m-tx-k8-node-1-yi6vhj-pigr5p0arj7kben1  Readiness probe failed: + source /conf/env.sh
++ DOMAIN=fed-kafka-affirmedzk-headless.fed-kafka.svc.cluster.local
++ QUORUM_PORT=2888
++ LEADER_PORT=3888
++ CLIENT_HOST=fed-kafka-affirmedzk-client
++ CLIENT_PORT=2181
+ source /usr/local/bin/zookeeperFunctions.sh
++ set -ex
++ hostname -s
+ HOST=fed-kafka-affirmedzk-1
+ DATA_DIR=/data
+ MYID_FILE=/data/myid
+ LOG4J_CONF=/conf/log4j-quiet.properties
++ echo ruok
++ nc 127.0.0.1 2181
(UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused

**Comment by anishakj** [comment]
Is the issue still seen with latest version?

**Comment by priyavj08** [comment]
@anishakj  
tried with latest version 0.2.9 and seeing issue in ZK pod bring up

attaching log files
[zk0.log](https://github.com/pravega/zookeeper-operator/files/5429148/zk0.log)
[zk1.log](https://github.com/pravega/zookeeper-operator/files/5429149/zk1.log)

**Comment by priyavj08** [comment]
@anishakj  also notice this error in events in describe pod

Events:
  Type     Reason     Age   From                                                     Message
  ----     ------     ----  ----                                                     -------
  Normal   Scheduled  25m   default-scheduler                                        Successfully assigned fed-kafka/fed-kafka-affirmedzk-0 to priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8
  Normal   Pulling    25m   kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Pulling image "pravega/zookeeper:0.2.9"
  Normal   Pulled     25m   kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Successfully pulled image "pravega/zookeeper:0.2.9"
  Normal   Created    25m   kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Created container zookeeper
  Normal   Started    25m   kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Started container zookeeper
  Warning  Unhealthy  24m   kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Liveness probe failed: + source /conf/env.sh
++ DOMAIN=fed-kafka-affirmedzk-headless.fed-kafka.svc.cluster.local
++ QUORUM_PORT=2888
++ LEADER_PORT=3888
++ CLIENT_HOST=fed-kafka-affirmedzk-client
++ CLIENT_PORT=2181
++ CLUSTER_NAME=fed-kafka-affirmedzk
++ CLUSTER_SIZE=3
++ echo ruok
++ nc 127.0.0.1 2181
(UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused
+ OK=
  Warning  Unhealthy  24m  kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Readiness probe failed: + source /conf/env.sh
++ DOMAIN=fed-kafka-affirmedzk-headless.fed-kafka.svc.cluster.local
++ QUORUM_PORT=2888
++ LEADER_PORT=3888
++ CLIENT_HOST=fed-kafka-affirmedzk-client
++ CLIENT_PORT=2181
++ CLUSTER_NAME=fed-kafka-affirmedzk
++ CLUSTER_SIZE=3
+ source /usr/local/bin/zookeeperFunctions.sh
++ set -ex
++ hostname -s
+ HOST=fed-kafka-affirmedzk-0
+ DATA_DIR=/data
+ MYID_FILE=/data/myid
+ LOG4J_CONF=/conf/log4j-quiet.properties
+ STATIC_CONFIG=/data/conf/zoo.cfg
++ echo ruok
++ nc 127.0.0.1 2181
(UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused
+ OK=

**Comment by priyavj08** [comment]
@anishakj  any thoughts on this? should I try a version before this?  please help  

thanks
Priya

**Comment by priyavj08** [comment]
@anishakj tried with version 0.2.7 and the operator pod doesn't come up, see this error in the describe events of the pod

 Warning  Unhealthy  5s (x31 over 5m5s)  kubelet, priya-vijaya-k8-node-2-a00034-4b2c09f7b029c1b8  Readiness probe failed: stat: can't stat '/tmp/operator-sdk-ready': No such file or directory

**Comment by anishakj** [comment]
Could  you please share me the operator yaml file used?

**Comment by priyavj08** [comment]
@anishakj after removing the readiness probe check from operator yaml it is working fine. 

but I am back to error where zk-1 is in crashloopbackoff state with error

 Unexpected exception, exiting abnormally
java.lang.RuntimeException: My id 2 not in the peer list
        at org.apache.zookeeper.server.quorum.QuorumPeer.start(QuorumPeer.java:1073)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.runFromConfig(QuorumPeerMain.java:227)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:136)
        at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:90)
2020-10-27 09:59:34,635 [myid:2] - INFO  [main:ZKAuditProvider@42] - ZooKeeper audit is disabled.
2020-10-27 09:59:34,736 [myid:2] - ERROR [main:ServiceUtils@42] - Exiting JVM with code 1


kubectl describe pod showing event
UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused
+ OK=
  Warning  Unhealthy  113s (x3 over 3m24s)  kubelet, priya-vijaya-k8-node-1-a00034-4b2c09f7b029c1b8  Liveness probe failed: + source /conf/env.sh
++ DOMAIN=fed-kafka-affirmedzk-headless.fed-kafka.svc.cluster.local
++ QUORUM_PORT=2888
++ LEADER_PORT=3888
++ CLIENT_HOST=fed-kafka-affirmedzk-client
++ CLIENT_PORT=2181
++ CLUSTER_NAME=fed-kafka-affirmedzk
++ CLUSTER_SIZE=3
++ echo ruok
++ nc 127.0.0.1 2181
(UNKNOWN) [127.0.0.1] 2181 (?) : Connection refused
+ OK=
  Warning  BackOff  104s (x2 over 106s)  kubelet, priya-vijaya-k8-node-1-a00034-4b2c09f7b029c1b8  Back-off restarting failed container

**Comment by anishakj** [comment]
Which envirionment are you trying , is it a minikube?

**Comment by priyavj08** [comment]
@anishakj no it is not minikube. it is kubernetes version 1.18

**Comment by anishakj** [comment]
From the logs shared I am seeing
```2020-10-23 11:07:15,444 [myid:1] - ERROR [LearnerHandler-/192.168.135.47:36144:LearnerHandler@707] - Unexpected exception causing shutdown while sock still open
java.io.EOFException
	at java.base/java.io.DataInputStream.readInt(Unknown Source)
	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:96)
	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:86)
	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:134)
	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:643)
2020-10-23 11:07:15,445 [myid:1] - WARN  [LearnerHandler-/192.168.135.47:36144:LearnerHandler@730] - ******* GOODBYE /192.168.135.47:36144 ********
2020-10-23 11:07:15,627 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@600] - Expiring session 0x1002e17944c000c, timeout of 4000ms exceeded```

**Comment by priyavj08** [comment]
oh ok what can cause this? any config I am missing?

**Comment by anishakj** [comment]
Can you try it on minikube?(https://github.com/pravega/zookeeper-operator#installation-on-minikube). We have tried in multiple environments, didn't see this issue.

**Comment by priyavj08** [comment]
works for me with quorumListenOnAllIPs set to true although not running in istio mesh, may be something specific to my environment

closing this issue
