### ISSUE TITLE
Helm chart version differs from pravega/charts

### ISSUE THREAD

**Issue by dalbani** [pravega/zookeeper-operator#265]
### Description

The ZooKeeper [operator] Helm charts provided in https://github.com/pravega/charts/tree/master/docs have recently been updated to version 0.2.9.
But the version in this repository is still 0.2.8:
- https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/Chart.yaml
- https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/Chart.yaml

### Importance

Not so important in itself, because the charts at version 0.2.9 are available.

### Location

https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/

### Suggestions for an improvement

Could you explain how the charts in https://github.com/pravega/charts/ are produced? I though it was based on the code provided in this repository. But maybe it is actually the case??

**Comment by SrishT** [comment]
@dalbani yes the charts are actually based on the code provided in this repository. The version here however needs to be updated.
