### ISSUE TITLE
Automating the release process

### ISSUE THREAD

**Issue by spiegela** [pravega/zookeeper-operator#266]
### Description

The release job in travis is failing to push docker images out in the release process.  The user credentials for the Docker reigstry must have changed, and were not updated in the encrypted Travis configuration

https://travis-ci.org/github/pravega/zookeeper-operator/jobs/736353355

```
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
Makefile:84: recipe for target 'login' failed
make: *** [login] Error 1
Script failed with status 2
```

### Importance

❗ Critical ❗ 

### Location

https://github.com/pravega/zookeeper-operator/blob/master/.travis.yml#L12

### Suggestions for an improvement

Fix the credentials to allow docker push

**Comment by anishakj** [comment]
@spiegela We are pushing the images to docker hub manually as of now. This is done because the  `make push` won't tag the images properly. It is not a broken functionality.
