### ISSUE TITLE
zookeeper metrics

### ISSUE THREAD

**Issue by lengrongfu** [pravega/zookeeper-operator#287]
### Description
   Is there a plan to add the default indicator collector to the operator and grab it through Prometheus?

**Comment by lengrongfu** [comment]
If there is no plan, I can contribute.

**Comment by anishakj** [comment]
Please go ahead

**Comment by lengrongfu** [comment]
assign to me.

**Comment by lengrongfu** [comment]
Regarding this metrics feature support, I found that this project has done a lot of things and can export` jmx`, so now I think what I can do is to add a `servicemonitor.yaml ` file to the project. If you think this is unnecessary, Then I will close this issue.

**Comment by anishakj** [comment]
@lengrongfu Currently, we are enabling the metrics via Prometheus and is added in the configuration https://github.com/pravega/zookeeper-operator/blob/master/pkg/zk/generators.go#L260-L262  You will be able to display the metrics in grafana as well(https://zookeeper.apache.org/doc/current/zookeeperMonitor.html)

Please let us know if any other support is needed ?

**Comment by anishakj** [comment]
Closing this  issue, Please feel free to reopen if any enhancement is required on this.
