### ISSUE TITLE
Helm config spec cannot be set because the some paths are incorrect

### ISSUE THREAD

**Issue by kentakozuka** [pravega/zookeeper-operator#299]
### Description

In the zookeeper helm chart, some config specs cannot be set because the paths are incorrect.
They should be;

```
    {{- if .Values.config.xxxx}}
    xxxx: {{ .Values.config.xxxx }}
    {{- end }}
```

But in some lines, they are;

```
    {{- if .Values.config.xxxx}}
    xxxx: {{ .Values.xxxx }}
    {{- end }}
```

### Location

https://github.com/pravega/zookeeper-operator/blob/b50eaa4565b8643cecf9fb1216a5470d8efb4423/charts/zookeeper/templates/zookeeper.yaml#L91-L137

### Suggestions for an improvement

It is necessary to set correct paths.

**Comment by SrishT** [comment]
@kentakozuka this would require a minor fix. Would u like to send out a PR in order to fix this issue?
