### ISSUE TITLE
chart: some api object deprecated

### ISSUE THREAD

**Issue by cospotato** [pravega/zookeeper-operator#302]
### Description

`apiextensions.k8s.io/v1beta1 CustomResourceDefinition` will unavailable in `v1.22+`

```
W1229 13:53:17.506965   95724 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1229 13:53:17.508219   95724 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
W1229 13:53:17.557191   95724 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1229 13:53:17.560014   95724 warnings.go:67] rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
```

### Importance

_should-have_

### Location

https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml

### Suggestions for an improvement

Maybe add `Capabilities` object to check cluster capabilities?

**Comment by baluchicken** [comment]
Are there any updates on this when this will be available? Thanks

**Comment by anishakj** [comment]
@baluchicken https://github.com/pravega/zookeeper-operator/pull/330 will fix this issue as well

**Comment by anishakj** [comment]
Fixed by PRhttps://github.com/pravega/zookeeper-operator/pull/330
