### ISSUE TITLE
increase Max and Min session timeout didn't take effect into zookeeper configuration

### ISSUE THREAD

**Issue by Biga-incorta** [pravega/zookeeper-operator#310]
Hi Guys,

I tried the following 
`helm install zookeeper pravega/zookeeper --version=0.2.9 --set config.tickTime=3000 --set config.maxClientCnxns=120   --set config.minSessionTimeout=2000 --set config.maxSessionTimeout=900000 `

but when open the configmap I didn't see minSessionTimeout, maxSessionTimeout or maxClientCnxns only the tickTime changed from default 2000 into 3000.

What is wrong?

**Comment by anishakj** [comment]
@Biga-incorta  these  changes are not available in `0.2.9` release. It will be there in the coming release.
