### ISSUE TITLE
[Bug]: Pod.securityContext setting in zookeeper chart values.yaml disappear in created zookeeper StatefulSet

### ISSUE THREAD

**Issue by gxglls** [pravega/zookeeper-operator#333]
### Description

Pod.securityContext setting in zookeeper chart values.yaml disappear in created zookeeper StatefulSet.

### Importance

must-have

### Location

https://github.com/gxglls/zookeeper-operator/blob/fd714b40e4148221dd9ab0c27b5693f51a95ee2a/pkg/zk/generators.go#L108
```golang
if reflect.DeepEqual(v1.PodSecurityContext{}, z.Spec.Pod.SecurityContext) { // should !reflect.DeepEqual() here
    podSpec.SecurityContext = z.Spec.Pod.SecurityContext	
}
```

### Suggestions for an improvement
Fixed by myself in related pr

**Comment by anishakj** [comment]
@gxglls Do you wish to contribute by raising PR?

**Comment by gxglls** [comment]
> @gxglls Do you wish to contribute by raising PR?

@anishakj  related PR https://github.com/pravega/zookeeper-operator/pull/334, thanks
