### ISSUE TITLE
[Question] What is the release plan for this project？

### ISSUE THREAD

**Issue by gxglls** [pravega/zookeeper-operator#337]
I want to know when the next version such as 0.2.11 is released, because my project relies on some of the latest commits on the master branch, or does the project have a corresponding communication group such as Slack? Thank you very much

**Comment by anishakj** [comment]
@gxglls We are planning to the release by end of next week. will keep you posted

**Comment by gxglls** [comment]
@anishakj thanks

**Comment by gxglls** [comment]
@anishakj Is the release still going according to plan？I will try my best to help if there is any need for help, thank you

**Comment by anishakj** [comment]
> @anishakj Is the release still going according to plan？I will try my best to help if there is any need for help, thank you
> 
> @gxglls We are just waiting for the couple of PRs to get merged, before making the release

@gxglls  New release`0.2.11` is now available.
