### ISSUE TITLE
[bug]: ZookeeperCluster crd's status disappear

### ISSUE THREAD

**Issue by gxglls** [pravega/zookeeper-operator#350]
### Description

ZookeeperCluster crd's status disappear when install zookeeper-operator/zookeeper version 0.2.11，there are no fields in ZookeeperCluster crd's status when zk-operator/zookeeper pod running.

ZookeeperCluster crd's status display current in zookeeper-operator/zookeeper version 0.2.8.

### Importance

must-have

**Comment by anishakj** [comment]
@gxglls what is the kubernetes version in your  cluster?

**Comment by anishakj** [comment]
i am able to see the status as below
 ```
 kubectl get zk -n pravega-test
NAME        REPLICAS   READY REPLICAS   VERSION              DESIRED VERSION      INTERNAL ENDPOINT   EXTERNAL ENDPOINT   AGE
zookeeper   3          3                0.2.10-177-ba22332   0.2.10-177-ba22332   172.30.94.28:2181   N/A                 20d
```

**Comment by gxglls** [comment]
```
root@ziyin-k8s-clean:/root # kubectl get pod
NAME                                  READY   STATUS    RESTARTS   AGE
zookeeper-0                           1/1     Running   1          2m49s
zookeeper-1                           1/1     Running   1          77s
zookeeper-2                           1/1     Running   0          53s
zookeeper-operator-7fc7b5fcf6-k27qs   1/1     Running   0          14m

root@ziyin-k8s-clean:/root # kubectl get zk
NAME        REPLICAS   READY REPLICAS   VERSION   DESIRED VERSION   INTERNAL ENDPOINT   EXTERNAL ENDPOINT   AGE
zookeeper   3                                     0.2.11
```

**Comment by gxglls** [comment]
> i am able to see the status as below
> 
> ```
> kubectl get zk -n pravega-test
> NAME        REPLICAS   READY REPLICAS   VERSION              DESIRED VERSION      INTERNAL ENDPOINT   EXTERNAL ENDPOINT   AGE
> zookeeper   3          3                0.2.10-177-ba22332   0.2.10-177-ba22332   172.30.94.28:2181   N/A                 20d
> ```

try 0.2.11?

**Comment by anishakj** [comment]
> > i am able to see the status as below
> > ```
> > kubectl get zk -n pravega-test
> > NAME        REPLICAS   READY REPLICAS   VERSION              DESIRED VERSION      INTERNAL ENDPOINT   EXTERNAL ENDPOINT   AGE
> > zookeeper   3          3                0.2.10-177-ba22332   0.2.10-177-ba22332   172.30.94.28:2181   N/A                 20d
> > ```
> 
> try 0.2.11?

It is showing there as well
```
kubectl get zk
NAME        REPLICAS   READY REPLICAS   VERSION   DESIRED VERSION   INTERNAL ENDPOINT     EXTERNAL ENDPOINT   AGE
zookeeper   3          3                0.2.11    0.2.11            10.100.200.143:2181   N/A                 2m33s
```

**Comment by anishakj** [comment]
> > > i am able to see the status as below
> > > ```
> > > kubectl get zk -n pravega-test
> > > NAME        REPLICAS   READY REPLICAS   VERSION              DESIRED VERSION      INTERNAL ENDPOINT   EXTERNAL ENDPOINT   AGE
> > > zookeeper   3          3                0.2.10-177-ba22332   0.2.10-177-ba22332   172.30.94.28:2181   N/A                 20d
> > > ```
> > 
> > 
> > try 0.2.11?
> 
> It is showing there as well
> 
> ```
> kubectl get zk
> NAME        REPLICAS   READY REPLICAS   VERSION   DESIRED VERSION   INTERNAL ENDPOINT     EXTERNAL ENDPOINT   AGE
> zookeeper   3          3                0.2.11    0.2.11            10.100.200.143:2181   N/A                 2m33s
> ```

Which is the API version of CRD in your cluster, in my cluster it is `v1beta1`

**Comment by anishakj** [comment]
@gxglls I am able to reproduce the issue with CRD version `v1`
