### ISSUE TITLE
ZK ensemble lost quorum and lots of exceptions seen in all ZK pods

### ISSUE THREAD

**Issue by priyavj08** [pravega/zookeeper-operator#376]
### Description

ZK ensemble is in a state where it looks like quorum is lost and see bunch of I/O exceptions .  ZK cluster is not recovering from this state.

 Log files have exceptions "Zookeeper is not running" but on exec to pod and running command it seems ok
echo ruok | nc 127.0.0.1 2181
imok

also see this error in the operator log
{"level":"error","ts":1627540813.2961993,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"zookeepercluster-controller","request":"fed-kafka/fed-kafka-affirmedzk","error":"Operation cannot be fulfilled on zookeeperclusters.zookeeper.pravega.io \"fed-kafka-affirmedzk\": the object has been modified; please apply your changes to the latest version and try again",

### Importance
This affects the Kafka cluster as well and is important ZK cluster remains stable

### Location

ZK Quorum

**Comment by priyavj08** [comment]
[zkop.txt](https://github.com/pravega/zookeeper-operator/files/6901285/zkop.txt)
[zk0log.txt](https://github.com/pravega/zookeeper-operator/files/6901289/zk0log.txt)
[zk1log.txt](https://github.com/pravega/zookeeper-operator/files/6901292/zk1log.txt)
[zk2log.txt](https://github.com/pravega/zookeeper-operator/files/6901293/zk2log.txt)

**Comment by anishakj** [comment]
@priyavj08 which is the version of zookeeper-operator are you using? Could you please try in `0.2.12` and let us know.

**Comment by priyavj08** [comment]
@anishakj I am using 0.2.10

do you think these issues won't happen in 0.2.12?

thanks

**Comment by anishakj** [comment]
> @anishakj I am using 0.2.10
> 
> do you think these issues won't happen in 0.2.12?
> 
> thanks

The error message you have mentioned got fixed by PR https://github.com/pravega/zookeeper-operator/pull/367

**Comment by anishakj** [comment]
> > @anishakj I am using 0.2.10
> > do you think these issues won't happen in 0.2.12?
> > thanks
> 
> The error message you have mentioned got fixed by PR #367

@priyavj08 is your issue got solved?

**Comment by priyavj08** [comment]
@anishakj  you can close this issue. We are yet to update in production, will try and let you know.

thanks

**Comment by anishakj** [comment]
Closing this issue as it got fixed in `0.2.12`
