### ISSUE TITLE
Changing Zookeeper resource "storage" value through `kubectl edit` not reflecting 

### ISSUE THREAD

**Issue by deenav** [pravega/zookeeper-operator#40]
**Changing Zookeeper resource "storage" values through `kubectl edit` not reflecting for new/scaledup zookeeper pods**

Increasing the zookeeper storage size does not work for the already deployed zookeeper pods & also for the new/scaledup pods.

```
# kubectl edit zk some-zookeeper-cluster -n some-namespace
...
    resources:
      requests:
        storage: 20Gi  --> Increased to 50Gi
...
```

**Comment by spiegela** [comment]
@deenav Kubernetes stateful-sets do not support changing a storage volume; therefore, the zookeeper spec will not support this either. The correct behavior will be to return an error when editing a resource with an increased storage size, which I will create an issue for.

**Comment by spiegela** [comment]
SIG Apps and SIG Storage are collaborating on a solution for this. Once volume expansion is supported in stateful-sets we will enable it in the ZK Operator.
