### ISSUE TITLE
Harden zookeeper post install hook

### ISSUE THREAD

**Issue by anishakj** [pravega/zookeeper-operator#417]
### Description

Zookeeper post install hook is  succeeding  before all zookeeper pods are becoming ready
### Importance

must-have

### Location

post-install-upgrade-hooks.yaml

### Suggestions for an improvement

Harden the checks in post-install hook.

**Comment by RangaSamudrala** [comment]
Hello, 
I have downloaded latest code and tried to run the zookeeper installer on Minikube. I still see problem that may have been targeted with this fix: 

`> charts % helm install zookeeper zookeeper --values zookeeper/values/minikube.yaml --debug
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /Users/ranganathsamudrala/Documents/Projects/helm/zookeeper-operator/charts/zookeeper

client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zookeeper-post-install-upgrade" ServiceAccount
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zookeeper-post-install-upgrade" ConfigMap
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zookeeper-post-install-upgrade" Role
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zookeeper-post-install-upgrade" RoleBinding
client.go:128: [debug] creating 1 resource(s)
client.go:299: [debug] Starting delete for "zookeeper-post-install-upgrade" Job
client.go:328: [debug] jobs.batch "zookeeper-post-install-upgrade" not found
client.go:128: [debug] creating 1 resource(s)
client.go:528: [debug] Watching for changes to Job zookeeper-post-install-upgrade with timeout of 5m0s
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: ADDED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: MODIFIED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: MODIFIED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: MODIFIED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 1, jobs failed: 2, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: MODIFIED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 1, jobs failed: 3, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: MODIFIED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 1, jobs failed: 4, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for zookeeper-post-install-upgrade: MODIFIED
client.go:595: [debug] zookeeper-post-install-upgrade: Jobs active: 1, jobs failed: 5, jobs succeeded: 0
client.go:299: [debug] Starting delete for "zookeeper-post-install-upgrade" Job
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:88: [debug] failed post-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581`

`> kc logs --follow job.batch/zookeeper-post-install-upgrade
Checking for ready ZK replicas
ZK replicas not ready
`

`> kc get all                                   
NAME                                                                     READY   STATUS    RESTARTS   AGE
pod/zookeeper-0                                                    1/1          Running     0                46s
pod/zookeeper-operator-f579bfcf5-22jdp           1/1         Running     0                106m
pod/zookeeper-post-install-upgrade--1-rnm7b   0/1         Error          0                67s
pod/zookeeper-post-install-upgrade--1-w7qrq    0/1         Error          0                35s

NAME                                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                                        AGE
service/kubernetes                          ClusterIP   10.96.0.1             <none>           443/TCP                                        153m
service/zookeeper-admin-server   ClusterIP   10.102.46.65       <none>           8080/TCP                                       67s
service/zookeeper-client                 ClusterIP   10.106.195.134   <none>             2181/TCP                                       67s
service/zookeeper-headless           ClusterIP    None                   <none>        2181/TCP,2888/TCP,3888/TCP,7000/TCP,8080/TCP   67s

NAME                                                    READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/zookeeper-operator   1/1               1                      1           106m

NAME                                           DESIRED   CURRENT   READY   AGE
replicaset.apps/zookeeper-operator-f579bfcf5   1         1         1       106m

NAME                                    READY   AGE
statefulset.apps/zookeeper   1/1         67s

NAME                                                          COMPLETIONS   DURATION   AGE
job.batch/zookeeper-post-install-upgrade   0/1                          67s        67s`


Do we even need this logic below [Line#65](https://github.com/pravega/zookeeper-operator/pull/418/commits/6b02e70e4f6609218cdde239d9564a5055e1c15f#L65)

`    echo "Checking for ready ZK replicas"
    kubectl get ZookeeperCluster -n {{ .Release.Namespace }} {{ template "zookeeper.fullname" . }}  -o jsonpath='{.status.conditions[?(@.type=="PodsReady")].status}' | grep True
    if [ $? != 0 ]; then
        echo "ZK replicas not ready"
        exit 1
    fi`
