### ISSUE TITLE
Add support for topologySearchConstraints in Zookeeper helm charts

### ISSUE THREAD

**Issue by RangaSamudrala** [pravega/zookeeper-operator#427]
### Description

_Add support for [topologySpreadConstraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) in Zookeeper helm charts

### Importance

_should-have_

### Location

[_zookeeper.yaml_](https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper/templates/zookeeper.yaml)

### Suggestions for an improvement

_Very similar to how support is provided for POD anti-affinity_

**Comment by endzyme** [comment]
This would be great to have at some point.
