### ISSUE TITLE
policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+

### ISSUE THREAD

**Issue by cbuto** [pravega/zookeeper-operator#428]
### Description

The `PodDisruptionBudget` created for zookeeper clusters needs to be updated to use `policy/v1`.

```
W0124 15:31:48.254050       1 warnings.go:67] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```

### Importance

This is fairly low importance right now but should be addressed before 1.25+ (which is a ways out)

### Location

https://github.com/pravega/zookeeper-operator/blob/master/pkg/controller/zookeepercluster/zookeepercluster_controller.go#L529
https://github.com/pravega/zookeeper-operator/blob/3359647e5044ed1e9918e84eae425136328b7709/pkg/zk/generators.go#L355

### Suggestions for an improvement

I'm not sure what the Kubernetes version support looks like for this project, but `policy/v1` is only available in 1.21+ clusters so that's something to consider.

**Comment by cbuto** [comment]
thanks @anishakj! 

Is there a release cadence or do you have an idea of when the next release would be?

**Comment by cbuto** [comment]
👋 friendly ping @anishakj about the above ^

**Comment by anishakj** [comment]
@TeddyAndrieux we will do it by end of this month.

**Comment by TeddyAndrieux** [comment]
Perfect, thank you :+1:

**Comment by TomBillietKlarrio** [comment]
We'd also appreciate a release since we're working to upstep to 1.25 :pray: 
Thanks upfront!
