### ISSUE TITLE
ZK-operator pre-delete hook fails in slow environments

### ISSUE THREAD

**Issue by nishant-yt** [pravega/zookeeper-operator#432]
### Description

Currently in the pre delete hook script in zookkeeper operator charts, the `activeDeadineSeconds` is being set to `20`. But In some environments the pre-delete hook takes more than 20 seconds to complete and because of this job fails . Moreover once the job is failed , the operator chart cannot be uninstalled normally.

### Importance

must-have

### Location

https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/templates/pre-delete-hooks.yaml

### Suggestions for an improvement

 Need to remove `activeDeadlineSeconds` from the hook job spec to let the hook script run as long as needed and increase the `backoffLimit` say to 6  to allow for easier debugging of failed pods

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/441
