### ISSUE TITLE
readme file error

### ISSUE THREAD

**Issue by happyboy1986** [pravega/zookeeper-operator#481]
### Description

_(Describe the feature, bug, question, proposal that you are requesting)_
kubectl create -f deploy/manager/manager.yaml

### Importance

_(Indicate the importance of this issue to you (blocker, must-have, should-have, nice-to-have))_
kubectl create -f config/manager/manager.yaml
### Location

_(Where is the piece of code, package, or document affected by this issue?)_

### Suggestions for an improvement

_(How do you suggest to fix or proceed with this issue?)_

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/488
