### ISSUE TITLE
The CustomResourceDefinition "zookeeperclusters.zookeeper.pravega.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema

### ISSUE THREAD

**Issue by lunarfs** [pravega/zookeeper-operator#486]
### Description
when applying  zookeeper.pravega.io_zookeeperclusters_crd.yaml I am getting 
`The CustomResourceDefinition "zookeeperclusters.zookeeper.pravega.io" is invalid: spec.preserveUnknownFields: Invalid value: true: must be false in order to use defaults in the schema`
we are running k8s 1.21.2 and have been changing 
`apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` (This is an old cluster that has been undergoing many upgrades, and the operator was installed when the cluster had`apiextensions.k8s.io/v1beta1` 
I am upgrading the operator from 0.13 to 0.14
so reading https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
suggest that the CRD should 
1) Use a structural OpenAPI schema.
2) Set `spec.preserveUnknownFields` to `false`.
so i manually edited the CRD to have `spec.preserveUnknownFields` to `false` and i was able to apply the CRD fo 0.24 

### Importance
should-have ( i guess)

### Location
charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml

### Suggestions for an improvement
Set `spec.preserveUnknownFields` to `false`.
it seems that the Crd has `crd.openAPIV3Schema` when on  `apiextensions.k8s.io/v1` so i guess just adding `spec.preserveUnknownFields` with the value `false` when on  `apiextensions.k8s.io/v1` should be fine 
so something like
```
{{- if not (.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1") }}
  preserveUnknownFields: false
  subresources:
    status: {}
  validation:
{{- include "crd.openAPIV3Schema" . | indent 4}}
```

**Comment by anishakj** [comment]
@lunarfs As of now all components are updated to `v1`. There is no support for `v1beta1`

**Comment by lunarfs** [comment]
so digging a bit further into this it seems that `charts/zookeeper-operator/templates/zookeeper.pravega.io_zookeeperclusters_crd.yaml` has been totally rewritten between 0.14 and master.
I did an upgrade on another cluster where the CRD where installed 6 months later (dec 2021) and here the upgrade ran trough..
@anishakj the issue is not with `v1` vs `v1beta` but rather if the CRD was installed when the cluster was running `apiextensions.k8s.io/v1beta1` and then the cluster was upgraded to `apiextensions.k8s.io/v1` then the field `spec.preserveUnknownFields: true` and applying the upgrade fails. explicitly setting `spec.preserveUnknownFields: true` as sugested in https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/ makes the upgrade go trough.. 
i am not sure how or if this should be fixed.. Maybe it is enough for people running into this just to set the value in the crd like my proposal above... and then get on wit using the operator.

**Comment by lunarfs** [comment]
@anishakj I am closing this issue, as manually setting spec.preserveUnknownFields: false solved the issue for me, and it is only an issue if you are running old versions of k8s under certain conditions that you will face this issue, unlikely that it will happen for a lot  of users

**Comment by nandanrao** [comment]
Thanks @lunarfs! 

For what it's worth, I ran into this same problem, trying to upgrade from 0.2.6. 

I was able to:

`kubectl edit crd zookeeperclusters.zookeeper.pravega.io`

And set `spec.preserveUnknownFields: false`

After which point I was able to upgrade to 0.2.14.
