### ISSUE TITLE
missing deply directory

### ISSUE THREAD

**Issue by only21tender** [pravega/zookeeper-operator#487]
In tag v0.2.14 branch , missing deploy directory . Is't normal?

**Comment by Wexxion** [comment]
If you trying to install zk operator via command `kubectl create -f deploy/manager/manager.yaml` from readme, and it fails, you should change `deploy` to 'config' dir

`kubectl create -f config/manager/manager.yaml`

**Comment by anishakj** [comment]
@Wexxion Would you like to create a PR for updating README doc

**Comment by Wexxion** [comment]
@anishakj yep

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/zookeeper-operator/pull/488
