### ISSUE TITLE
zookeeper stuck in upgrade, cluster seems to be upgraded, alle nodes running the new version, and ready

### ISSUE THREAD

**Issue by lunarfs** [pravega/zookeeper-operator#493]
### Description
cluster is stuck in upgrade, but cluster seems to be ready and upgraded
zookeeper   3          2                3.7.0_0.2.14_2022-08-10   3.7.0_0.2.14_2022-08-29   172.18.81.155:2181   N/A                 91d
so the upgrade was a 0.2.14 running zookeeper 3.7.0, where the baseimage was patched with a few security issues so the same zookeeper and operator, we are doing this regularly, and it usually works, but has also failed a few times. what I have done so-far is to delete the cluster and start over again.. but I really want to mature this (also starting over with a new zk cluster involves some work)

below is the output of 
`kubectl  -n zookeeper get pods -o json | jq -r .items[].status `
`{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:03:38Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:18Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:18Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:03:38Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://c7ae21de50fe3be1964501b78742054c5dba8a63a14c044ffd7b6650c9851f6b",
      "image": "ivanhub.azurecr.io/pravega_zookeeper:3.7.0_0.2.14_2022-08-29",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper@sha256:aec74a365414dd61d6bbaa2d6178595daaf0729cf42ba55b8c3160ed464d96b5",
      "lastState": {},
      "name": "zookeeper",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T12:10:04Z"
        }
      }
    }
  ],
  "hostIP": "XXX",
  "phase": "Running",
  "podIP": "XX.36",
  "podIPs": [
    {
      "ip": "XX.36"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T12:03:38Z"
}
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:16:05Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:24:46Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:24:46Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:16:05Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://f7054bcf807c7e2d6d8c4d4d0b3674e153012f48fa1fc0141aef389ae4268941",
      "image": "ivanhub.azurecr.io/pravega_zookeeper:3.7.0_0.2.14_2022-08-29",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper@sha256:aec74a365414dd61d6bbaa2d6178595daaf0729cf42ba55b8c3160ed464d96b5",
      "lastState": {},
      "name": "zookeeper",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T12:24:33Z"
        }
      }
    }
  ],
  "hostIP": "XX",
  "phase": "Running",
  "podIP": "XX.91",
  "podIPs": [
    {
      "ip": "XX.91"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T12:16:05Z"
}
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:52Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:15:32Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:15:32Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T12:10:52Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://c4384f795654ccdb1491fb3cce44859297454abe49b79aecc4dac136e969c9dd",
      "image": "ivanhub.azurecr.io/pravega_zookeeper:3.7.0_0.2.14_2022-08-29",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper@sha256:aec74a365414dd61d6bbaa2d6178595daaf0729cf42ba55b8c3160ed464d96b5",
      "lastState": {},
      "name": "zookeeper",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T12:15:16Z"
        }
      }
    }
  ],
  "hostIP": "XX",
  "phase": "Running",
  "podIP": "XX.149",
  "podIPs": [
    {
      "ip": "XX.149"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T12:10:52Z"
}
{
  "conditions": [
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:56:44Z",
      "status": "True",
      "type": "Initialized"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:57:13Z",
      "status": "True",
      "type": "Ready"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:57:13Z",
      "status": "True",
      "type": "ContainersReady"
    },
    {
      "lastProbeTime": null,
      "lastTransitionTime": "2022-08-31T11:56:43Z",
      "status": "True",
      "type": "PodScheduled"
    }
  ],
  "containerStatuses": [
    {
      "containerID": "containerd://33b55840f56795b55594ad5c49bb96a1d917802ad1b598972fda45ec643a767a",
      "image": "ivanhub.azurecr.io/pravega_zookeeper_operator:0.2.14_2022-08-08",
      "imageID": "ivanhub.azurecr.io/pravega_zookeeper_operator@sha256:db55ab2ce4784bf78d41e3774ee2e74585c018190f03a8be83cfff5154fa8dd1",
      "lastState": {},
      "name": "zookeeper-operator",
      "ready": true,
      "restartCount": 0,
      "started": true,
      "state": {
        "running": {
          "startedAt": "2022-08-31T11:57:13Z"
        }
      }
    }
  ],
  "hostIP": "XX",
  "phase": "Running",
  "podIP": "XX.171",
  "podIPs": [
    {
      "ip": "XX.171"
    }
  ],
  "qosClass": "BestEffort",
  "startTime": "2022-08-31T11:56:44Z"
}
`
### Importance

must-have
### Location
zookeeper-operator
### Suggestions for an improvement
So what I am missing is the option of running commands against the operator to fix issues like this,
I am also not sure where to look for logfiles that would help fixing this isse

**Comment by lunarfs** [comment]
https://pravega.io/docs/snapshot/pravega-operator/rollback-cluster/

**Comment by lunarfs** [comment]
so I am not an Go expert (fare from) but if i read pkg/controller/zookeepercluster/zookeepercluster_controller.go line 220
```
	if instance.Status.IsClusterInUpgradeFailedState() {
		return nil
	}
```
I am wondering how to get the cluster to either role-back or continue the failed upgrade?
as of now I only see deleting the cluster and restoring a backup as a viable solution.. or am i completely not getting the Go code?
I would think that one could call 
updateStatefulSet in case  instance.Status.IsClusterInUpgradeFailedState returns true.
because the sts is fine in my case, and we are just missing a call to update the state (here is output of the sts status)
`kubectl -n zookeeper get sts
NAME        READY   AGE
zookeeper   3/3     91d
`
so I am thinking something like this would work
```
       if  instance.Status.IsClusterInUpgradeFailedState() {
		err = r.updateStatefulSet(instance, foundSts, sts)
		if err != nil {
			return err
		}
                if  instance.Status.IsClusterInUpgradeFailedState() {
		        return nil
		}
	}

```

**Comment by lunarfs** [comment]
> ```
>     if  instance.Status.IsClusterInUpgradeFailedState() {
>     	sts := zk.MakeStatefulSet(instance)
>     	if err = controllerutil.SetControllerReference(instance, sts, r.Scheme); err != nil {
>     		return err
>     	}
>     	foundSts := &appsv1.StatefulSet{}
>     	err = r.Client.Get(context.TODO(), types.NamespacedName{
>     		Name:      sts.Name,
>     		Namespace: sts.Namespace,
>     	}, foundSts)
>     	if err == nil {
>             err = r.updateStatefulSet(instance, foundSts, sts)
>             if err != nil {
>               return err
>             }
>         }
>         if  instance.Status.IsClusterInUpgradeFailedState() {
>            return nil
>         }
>     }
> ```
so this is not working but I get
foundSts.Status.Replicas:3,
foundSts.Status.ReadyReplicas:3
i am digging a bit further

**Comment by lunarfs** [comment]
so with this code change i was able to get my failed cluster upgrade to complete

`
func (r *ZookeeperClusterReconciler) reconcileStatefulSet(instance *zookeeperv1beta1.ZookeeperCluster) (err error) {

	// we cannot upgrade if cluster is in UpgradeFailed
	if instance.Status.IsClusterInUpgradeFailedState() {
		r.Log.Info("ZookeeperCluster upgrade in failed state")
		sts := zk.MakeStatefulSet(instance)
		if err = controllerutil.SetControllerReference(instance, sts, r.Scheme); err != nil {
			return err
		}
		r.Log.Info("ZookeeperCluster defined sts")
		foundSts := &appsv1.StatefulSet{}
		err = r.Client.Get(context.TODO(), types.NamespacedName{
			Name:      sts.Name,
			Namespace: sts.Namespace,
		}, foundSts)
		r.Log.Info("ZookeeperCluster defined foundSts")
		if err == nil {
			r.Log.Info("ZookeeperCluster check if failed cluster upgrade has been resolved")
			err = r.Client.Update(context.TODO(), foundSts)
			if err != nil {
				return err
			}
			if foundSts.Status.Replicas == foundSts.Status.ReadyReplicas && foundSts.Status.CurrentRevision == foundSts.Status.UpdateRevision {
				r.Log.Info("failed upgrade completed", "upgrade from:", instance.Status.CurrentVersion, "upgrade to:", instance.Status.TargetVersion)
				instance.Status.CurrentVersion = instance.Status.TargetVersion
				instance.Status.SetErrorConditionFalse()
				return r.clearUpgradeStatus(instance)
			}
		}
	}
`
the status is now
```
kubectl -n zookeeper get zk zookeeper
NAME        REPLICAS   READY REPLICAS   VERSION                   DESIRED VERSION           INTERNAL ENDPOINT    EXTERNAL ENDPOINT   AGE
zookeeper   3          3                3.7.0_0.2.14_2022-08-29   3.7.0_0.2.14_2022-08-29   XX:2181   N/A                 92d
```
the log from the server
```
{"level":"info","ts":1662040396.6573174,"logger":"controller_zookeepercluster","msg":"ZookeeperCluster upgrade in failed state","Request.Namespace":"zookeeper","Request.Name":"zookeeper"}
{"level":"info","ts":1662040396.6573758,"logger":"controller_zookeepercluster","msg":"ZookeeperCluster defined sts","Request.Namespace":"zookeeper","Request.Name":"zookeeper"}
{"level":"info","ts":1662040396.6574295,"logger":"controller_zookeepercluster","msg":"ZookeeperCluster defined foundSts","Request.Namespace":"zookeeper","Request.Name":"zookeeper"}
{"level":"info","ts":1662040396.657439,"logger":"controller_zookeepercluster","msg":"ZookeeperCluster check if failed cluster upgrade has been resolved","Request.Namespace":"zookeeper","Request.Name":"zookeeper"}
{"level":"info","ts":1662040396.6676545,"logger":"controller_zookeepercluster","msg":"failed upgrade completed","Request.Namespace":"zookeeper","Request.Name":"zookeeper","upgrade from:":"3.7.0_0.2.14_2022-08-10","upgrade to:":"3.7.0_0.2.14_2022-08-29"}
```
@anishakj 
so removing some of the debug messages from the code.. would it make sense to do a PR to contribute this back ?

**Comment by anishakj** [comment]
@lunarfs  It will be really great if you could raise the PR

**Comment by lunarfs** [comment]
> @lunarfs I have a question when the upgarde is failed first time, is there any error in operator logs? Also is the zookeeper pods updated to new image

So there are 22 entries in the log with _upgrade in progress_ each with 30 second between those, except for that nothing intersting in the logs.
So what happened is that there was an issue pulling the new image from the registry (DNS issue). After approx 30 minutes the pulling issue was fixed, and the last node got healthy (because it could now pull its image). I have a few clusters that ran into this issue, one of which is now fixed with this code change. the last on I will moste likely have to fix today.
so yes the pods got upgraded to the new image, only the operator kept staying in upgrade failed state. So we definetley hit this part of the code

`				err = checkSyncTimeout(instance, zookeeperv1beta1.UpdatingZookeeperReason, foundSts.Status.UpdatedReplicas, 10*time.Minute)
				if err != nil {
					instance.Status.SetErrorConditionTrue("UpgradeFailed", err.Error())
					return r.Client.Status().Update(context.TODO(), instance)`
