### ISSUE TITLE
Any plan to support aarch64?

### ISSUE THREAD

**Issue by audacioustux** [pravega/zookeeper-operator#500]
### Description

`standard_init_linux.go:228: exec user process caused: exec format error` on aarch64 architecture on oracle cloud ampere

### Suggestions for an improvement

add aarch64 as target in build pipeline

**Comment by mmoscher** [comment]
Same here when running on Google Cloud's Tau T2A GCE instances.
Supporting arm64 would also be interesting for local development on Apple's Silicons M1/M2 processors.

**Comment by mmoscher** [comment]
@audacioustux PR is raised, however I'm not sure if this will work at all because the available GHA CI pipeline is not used at all (IMHO). Cf. https://github.com/pravega/zookeeper-operator/pull/504
