### ISSUE TITLE
Add support for data-checking on container restart

### ISSUE THREAD

**Issue by spiegela** [pravega/zookeeper-operator#53]
Currently the zookeeper-operator assumes that if a restarted instance's `zoo.cfg.dynamic` is valid, then so is the rest of the information under `/data`. The zookeeper operator should detect that a pod has been restarted with a valid `zoo.cfg.dynamic`, and then check the status of the data, restoring or removing the data if necessary.

**Comment by pbelgundi** [comment]
This has been fixed recently.
