### ISSUE TITLE
Resource Status not updated 

### ISSUE THREAD

**Issue by jkhalack** [pravega/zookeeper-operator#54]
When deploying a zookeeper cluster with `0.2.0` zookeeper-operator, the `ZookeeperCluster` resource does not get the `Status` section updated and always stays at 
```
Status:
  External Client Endpoint:  
  Internal Client Endpoint:  
  Members:
    Ready:         <nil>
    Unready:       <nil>
  Ready Replicas:  0
  Replicas:        0
```

*Example:*
We've deployed a zk-cluster in namespace `test-project` that is supposed to have three replicas.
Inspecting the related stateful set reveals that there are indeed three replicas running in the system:
```
$kubectl get statefulsets -n test-project
NAME        DESIRED   CURRENT   AGE
zookeeper   3         3         53m
```

Inspecting the `ZookeeperCluster` existing in the project, we get the `Status` section showing zero replicas.
```
$kubectl describe zk zookeeper -n test-project
Name:         zookeeper
Namespace:    test-project
Labels:       <none>
Annotations:  <none>
API Version:  zookeeper.pravega.io/v1beta1
Kind:         ZookeeperCluster
Metadata:
  Creation Timestamp:  2019-03-01T19:08:21Z
  Generation:          1
  Owner References:
    API Version:           nautilus.dellemc.com/v1alpha1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  Project
    Name:                  test-project
    UID:                   60c9fb21-3c55-11e9-a64e-005056bdd0fa
  Resource Version:        620540
  Self Link:               /apis/zookeeper.pravega.io/v1beta1/namespaces/test-project/zookeeper-clusters/zookeeper
  UID:                     6117246e-3c55-11e9-a64e-005056bdd0fa
Spec:
  Config:
    Init Limit:  10
    Sync Limit:  2
    Tick Time:   2000
  Image:
    Pull Policy:  Always
    Repository:   emccorp/zookeeper
    Tag:          3.5.4-beta-operator
  Labels:
    App:      zookeeper
    Release:  zookeeper
  Persistence:
    Access Modes:
      ReadWriteOnce
    Data Source:  <nil>
    Resources:
      Requests:
        Storage:  20Gi
  Pod:
    Affinity:
      Pod Anti Affinity:
        Preferred During Scheduling Ignored During Execution:
          Pod Affinity Term:
            Label Selector:
              Match Expressions:
                Key:       app
                Operator:  In
                Values:
                  zookeeper
            Topology Key:  kubernetes.io/hostname
          Weight:          20
    Labels:
      App:      zookeeper
      Release:  zookeeper
    Resources:
    Termination Grace Period Seconds:  30
  Ports:
    Container Port:  2181
    Name:            client
    Container Port:  2888
    Name:            quorum
    Container Port:  3888
    Name:            leader-election
  Replicas:          3
  Size:              3
Status:
  External Client Endpoint:  
  Internal Client Endpoint:  
  Members:
    Ready:         <nil>
    Unready:       <nil>
  Ready Replicas:  0
  Replicas:        0
Events:            <none>
```

**Comment by jkhalack** [comment]
It seems to be the issue similar to #36.

**Comment by jkhalack** [comment]
Not sure if it is related, but I'm noticing that `Affinity` section used to refer to `zookeeper-headless` service in `0.1.1`, but now it refers to just `zookeeper`, and there is no `zookeeper` service present in the namespace.

**Comment by Tristan1900** [comment]
I just download the 0.2.0 release and create a zk cluster using a custom namespace, but everything seems fine with the status. Is there anything to notice to reproduce the bug?

**Comment by jkhalack** [comment]
> I just download the 0.2.0 release and create a zk cluster using a custom namespace, but everything seems fine with the status.

Could you post the status here?

**Comment by Tristan1900** [comment]
@jkhalack  Sure.
```
Status:
  External Client Endpoint:  N/A
  Internal Client Endpoint:  10.100.200.142:2181
  Members:
    Ready:
      zk-0
      zk-1
      zk-2
    Unready:       <nil>
  Ready Replicas:  3
  Replicas:        3
Events:            <none>
```

**Comment by jkhalack** [comment]
Thank you @Tristan1900 

We also have the following kind of  recurring errors in zookeeper-operaror logs:

```
{"level":"info","ts":1551712379.973085,"logger":"controller_zookeepercluster","msg":"Updating zookeeper status","Request.Namespace":"test-project","Request.Name":"zookeeper","StatefulSet.Namespace":"test-project","StatefulSet.Name":"zookeeper"}
{"level":"error","ts":1551712379.9745054,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"zookeepercluster-controller","request":"test-project/zookeeper","error":"the server could not find the requested resource (put zookeeper-clusters.zookeeper.pravega.io zookeeper)","stacktrace":"github.com/pravega/zookeeper-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/pravega/zookeeper-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/pravega/zookeeper-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/pravega/zookeeper-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/pravega/zookeeper-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/pravega/zookeeper-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/pravega/zookeeper-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/pravega/zookeeper-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/pravega/zookeeper-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/pravega/zookeeper-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/pravega/zookeeper-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/pravega/zookeeper-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
```

Was there any change from `0.1.1` to `0.2.0` that we might have missed?

**Comment by jkhalack** [comment]
We are seeing the same issue when deploying pravega with `0.2.2` pravega-operator. There is a reconciler error in zookeeper-operator logs, and zk resource status never gets updated.

**Comment by Tristan1900** [comment]
Thank you @jkhalack 
I feel that this is either a configuration error or an operator-sdk bug according to the log. The change is we use subresource for updating status and that perhaps is the root cause. Could you please show me the clusterrole and clusterrolebinding you are using right now? Also, what is the Kubernetes version you are using? Subresource is only supported v.1.11.0 afaik.

**Comment by jkhalack** [comment]
I have v1.11.2 for client and v1.12.4 for server.

**Comment by jkhalack** [comment]
Do I understand correctly that the user that deploys `zookeeper-operator` should have a clusterrole `cluster-admin`? 
Or should `zookeeper-operator` be granted this role?

**Comment by jkhalack** [comment]
Also I'm not sure why there is no namespace listed in the error message: `the server could not find the requested resource (put zookeeper-clusters.zookeeper.pravega.io zookeeper)`.
There is `test-project/zookeeper` in the request field, but then only `zookeeper` in the message.

**Comment by adrianmo** [comment]
@jkhalack the error is being caused by your CRD specification. Recently, both Zookeeper and Pravega operator added support for the Status endpoint, adding a `subresource` block at the bottom of the file. Most likely, your CRD spec has not been updated and, therefore, the Status endpoint is not enabled on your `ZookeeperCluster` resources, giving you those errors.

You can check an updated CRD spec in https://github.com/pravega/zookeeper-operator/blob/master/deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml#L36

Let me know if it works.

**Comment by jkhalack** [comment]
@adrianmo I did try with updated CRD, still no luck.

**Comment by jkhalack** [comment]
Turns out the updated CRD did not work on a cluster with an older version of Kubernetes (1.10.5).
Deploying it on a cluster with v1.12.4 Kubernetes worked (no zk-operator errors and updated status on zk-cluster resource).

**Comment by jkhalack** [comment]
@adrianmo and @Tristan1900 Thank you for the help!

I'm closing the issue.
The solution is to update the CRD spec as in https://github.com/pravega/zookeeper-operator/blob/master/deploy/crds/zookeeper_v1beta1_zookeepercluster_crd.yaml#L36 and use a cluster with 1.11.x Kubernetes version.
