### ISSUE TITLE
Wrong Cluster Membership in Dynamic Config File

### ISSUE THREAD

**Issue by RaulGracia** [pravega/zookeeper-operator#66]
**Problem description**
We have suspicions that Pravega components (e.g., BK, SSS) are having trouble to interact with Zookeeper sometimes, which leads to failures. In this sense, an hypothesis we have is that the configuration of Zookeeper may be behind those problems. In a simple experiment, we deployed 3 Zookeeper instances with the Zookeeper Operator, and in the dynamic config file of each instance, we see the following:

(zookeeper-0)
```
/ # cat /data/zoo.cfg.dynamic
server.1=zookeeper-0.zookeeper-headless.default.svc.cluster.local:2888:3888:participant;2181
```
(zookeeper-1)
```
/ # cat /data/zoo.cfg.dynamic
server.1=zookeeper-0.zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
server.2=zookeeper-1.zookeeper-headless.default.svc.cluster.local:2888:3888:observer;0.0.0.0:2181
```
(zookeeper-2)
```
/ # cat /data/zoo.cfg.dynamic
server.1=zookeeper-0.zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
server.2=zookeeper-1.zookeeper-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
server.3=zookeeper-2.zookeeper-headless.default.svc.cluster.local:2888:3888:observer;0.0.0.0:2181
```
So, apparently every Zookeeper instance has a different view of the cluster, which may lead to problems. According to the documentation of Zookeeper, all the instances should have a consistent configuration.

**Problem location**
Zookeeper operator dynamic config generation.

**Suggestions for an improvement**
At first glance, all the instances should have the same membership in `zoo.cfg.dynamic` with all the members of the Zookeeper cluster. Also, we may need to verify whether the role setting (observer/participant) is correctly set in this context.

**Comment by spiegela** [comment]
@RaulGracia I was able to replicate the behavior you described; however, even with the `/data/zoo.cfg.dynamic` files being out of date, I can see that the correct configuration is available via CLI. I connected to the container via `bash` and ran:
```
/zookeeper-3.5.4-beta/bin/zkCli.sh
<snip>
[zk: localhost:2181(CONNECTED) 0] config
server.1=example-0.example-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
server.2=example-1.example-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
server.3=example-2.example-headless.default.svc.cluster.local:2888:3888:participant;0.0.0.0:2181
version=10000001c
```

I'm not sure why ZooKeeper wouldn't be overwriting the `zoo.cfg.dynamic`...  according to the [dynamic reconfiguration docs](https://zookeeper.apache.org/doc/r3.5.2-alpha/zookeeperReconfig.html#sc_reconfig_file):
> The dynamic parameters are pushed by ZooKeeper and overwrite the dynamic configuration files on all servers. Thus, the dynamic configuration files on the different servers are usually identical (they can only differ momentarily when a reconfiguration is in progress, or if a new configuration hasn't propagated yet to some of the servers). Once created, the dynamic configuration file should not be manually altered.

I checked the permissions/ownership of the `zoo.cfg.dynamic` (`root`/644), and ZooKeeper is running as `root`.

**Comment by Tristan1900** [comment]
@spiegela I am also reproducing this error. I find if we have two nodes zk-0 and zk-1, when zk-1 is starting and tries to [reconfigure](https://github.com/pravega/zookeeper-operator/blob/master/docker/zu/src/main/java/io/pravega/zookeeper/Main.kt#L99), some error will happen in the zk-0. Here is the log in zk-0 when zk-1 starts. 
```
2019-06-12 01:41:50,472 [myid:1] - INFO  [ProcessThread(sid:1 cport:-1)::PrepRequestProcessor@474] - Incremental reconfig
2019-06-12 01:41:50,477 [myid:1] - WARN  [ProcessThread(sid:1 cport:-1)::QuorumPeer$QuorumServer@173] - Failed to resolve address: zk-1.zk-headless.default.svc.cluster.local
java.net.UnknownHostException: zk-1.zk-headless.default.svc.cluster.local
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at java.net.InetAddress.getByName(InetAddress.java:1077)
	at org.apache.zookeeper.server.quorum.QuorumPeer$QuorumServer.recreateSocketAddresses(QuorumPeer.java:171)
	at org.apache.zookeeper.server.quorum.QuorumPeer.recreateSocketAddresses(QuorumPeer.java:727)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:682)
	at org.apache.zookeeper.server.quorum.QuorumPeer.connectNewPeers(QuorumPeer.java:1519)
	at org.apache.zookeeper.server.quorum.QuorumPeer.setLastSeenQuorumVerifier(QuorumPeer.java:1556)
	at org.apache.zookeeper.server.quorum.Leader.propose(Leader.java:1074)
	at org.apache.zookeeper.server.quorum.ProposalRequestProcessor.processRequest(ProposalRequestProcessor.java:78)
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequest(PrepRequestProcessor.java:906)
	at org.apache.zookeeper.server.PrepRequestProcessor.run(PrepRequestProcessor.java:145)
2019-06-12 01:41:50,482 [myid:1] - WARN  [ProcessThread(sid:1 cport:-1)::QuorumCnxManager@660] - Cannot open channel to 2 at election address zk-1.zk-headless.default.svc.cluster.local:3888
java.net.UnknownHostException: zk-1.zk-headless.default.svc.cluster.local
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:638)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.connectOne(QuorumCnxManager.java:695)
	at org.apache.zookeeper.server.quorum.QuorumPeer.connectNewPeers(QuorumPeer.java:1519)
	at org.apache.zookeeper.server.quorum.QuorumPeer.setLastSeenQuorumVerifier(QuorumPeer.java:1556)
	at org.apache.zookeeper.server.quorum.Leader.propose(Leader.java:1074)
	at org.apache.zookeeper.server.quorum.ProposalRequestProcessor.processRequest(ProposalRequestProcessor.java:78)
	at org.apache.zookeeper.server.PrepRequestProcessor.pRequest(PrepRequestProcessor.java:906)
	at org.apache.zookeeper.server.PrepRequestProcessor.run(PrepRequestProcessor.java:145)
2019-06-12 01:41:50,483 [myid:1] - ERROR [ProcessThread(sid:1 cport:-1)::QuorumPeer@1564] - Error writing next dynamic config file to disk: 
2019-06-12 01:41:50,485 [myid:1] - ERROR [SyncThread:1:QuorumPeer@1596] - Error closing file:
```

**Comment by spiegela** [comment]
I do see some relevant errors in the logs:
```
2019-06-12 01:21:46,092 [myid:1] - ERROR [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1564] - Error writing next dynamic config file to disk:
2019-06-12 01:21:46,094 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):Leader@1264] - Have quorum of supporters, sids: [ [1],[1] ]; starting up and setting last processed zxid:
2019-06-12 01:21:46,095 [myid:1] - ERROR [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):QuorumPeer@1596] - Error closing file:
2019-06-12 01:21:46,105 [myid:1] - INFO  [QuorumPeer[myid=1](plain=/0.0.0.0:2181)(secure=disabled):CommitProcessor@255] - Configuring CommitProcessor with 1 worker threads.
```

Kind of light on the details, but it wasn't able to write the new config file...  Oh.... I wonder if its because `/conf/zoo.cfg` is non-writable.  This [SO post](https://stackoverflow.com/questions/46078804/is-zookeeper-reconfig-expected-to-update-the-zoo-cfg-dynamic-file) indicates that the `zoo.cfg` file needs to be updated to point it at a new file, instead of updating `zoo.cfg.dynamic in place.

**Comment by spiegela** [comment]
> Here is the log in zk-0 when zk-1 starts.

@Tristan1900 I think that these are expected. The leader election won't be able to contact the new nodes until they become ready -- even in they're in as an observer, because readiness is required for DNS resolution.  That error will clear up once the node is promoted to a participant, and the readiness check returns a non-zero result.

**Comment by spiegela** [comment]
If the issue is that `zoo.cfg` needs to be writable, we'll need to copy it from the config map into the `/data` directory alongside the dynamic config.

**Comment by Tristan1900** [comment]
Thanks for the clarification. And you are right about the cause, I just check `zoo.cfg`, it is indeed read-only.

**Comment by spiegela** [comment]
Yeah, the docs don't mention that the "static" configuration files _needs_
to be writable. I thought based on them that the `zookeeper.cfg.dynamic`
would be modified in place. A good test would be to add a line in the
`zookeeperStart.sh` to copy `/conf/zoo.cfg` to `/data` and update the
`ZOOCFGDIR` environment variable to `/data` in the container.

**Comment by fpj** [comment]
That's correct, the static configuration is updated according to this code:

https://github.com/apache/zookeeper/blob/f63a831d67bd12303a3e1578126f2a09819fecd5/zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumPeer.java#L1720

It needs to be able to create a new dynamic configuration file and update the static configuration file to point to the latest configuration (that's for restarts of the server).

One thing that is unclear to is where in this operator the reconfiguration is happening. I searched for the reconfiguration command, but found nothing, could you point me to it?

**Comment by pbelgundi** [comment]
I see that the static configuration file is writable by owner(root) :
```
/zookeeper-3.5.4-beta # ls -l /conf/zoo.cfg
lrwxrwxrwx    1 root     root            14 Jun 12 09:54 /conf/zoo.cfg -> ..data/zoo.cfg

/conf # ls -l ..data
lrwxrwxrwx    1 root     root            31 Jun 12 09:54 ..data -> ..2019_06_12_09_54_07.531847676

/conf/..2019_06_12_09_54_07.531847676 # ls -l zoo.cfg
-rw-r--r--    1 root     root           220 Jun 12 09:54 zoo.cfg
```

**Comment by spiegela** [comment]
> One thing that is unclear to is where in this operator the reconfiguration is happening. I searched for the reconfiguration command, but found nothing, could you point me to it?
@fpj Each node will start as an observer if it is not already part of the ensemble.  It uses the `zu` util in the container invoked by the [`zookeeperStart.sh`](https://github.com/pravega/zookeeper-operator/blob/master/docker/bin/zookeeperStart.sh#L101) script.  Then once started, if the zookeeper service is live, the readiness check script, `zookeeperReady.sh` will check to see if the node is a participant or observer. If it's an observer, it will [promote it here](https://github.com/pravega/zookeeper-operator/blob/master/docker/bin/zookeeperReady.sh#L58).

The `zu` util called in the shell scripts is a [Kotlin script here.](https://github.com/pravega/zookeeper-operator/blob/master/docker/zu/src/main/java/io/pravega/zookeeper/Main.kt)

I hope I did all of that right ;-) I read the docs like half a dozen times.

**Comment by pbelgundi** [comment]
"/conf" seems to be read-only as  the operator has mounted this volume as source for a config map.
```
pbelgundi@ubuntu:~$ kubectl exec -it example-0 -- sh
/zookeeper-3.5.4-beta # ls -l /conf/
total 0
lrwxrwxrwx    1 root     root            13 Jun 12 09:54 env.sh -> ..data/env.sh
lrwxrwxrwx    1 root     root            29 Jun 12 09:54 log4j-quiet.properties -> ..data/log4j-quiet.properties
lrwxrwxrwx    1 root     root            23 Jun 12 09:54 log4j.properties -> ..data/log4j.properties
lrwxrwxrwx    1 root     root            14 Jun 12 09:54 zoo.cfg -> ..data/zoo.cfg
/zookeeper-3.5.4-beta # touch /conf/just
touch: /conf/just: Read-only file system
/zookeeper-3.5.4-beta # ls -ld /conf
drwxrwxrwx    3 root     root          4096 Jun 12 09:54 /conf
```
ConfigMap source volumes typically tend to be read-only:
https://github.com/kubernetes/kubernetes/issues/62099

However, this also means that moving zoo.cfg to /data will make the ConfigMap inconsistent.

**Comment by pbelgundi** [comment]
Operator code that creates a config map on the "/conf" volume:
https://github.com/pravega/zookeeper-operator/blob/master/pkg/zk/generators.go#L104
https://github.com/pravega/zookeeper-operator/blob/master/pkg/zk/generators.go#L124

**Comment by pbelgundi** [comment]
Another way to solve this could be to remove the config map from zookeeper operator code and have a 'pvc' for mount volume "/conf" so changes are not lost with pod failures.
That way "/conf" will no longer be read-only and things would work as expected.

Right now, I don't think  Zookeeper uses the config map generated by zk-operator, since it is reading all configurations directly from files under /conf.....and this just causes trouble with updating the configurations...

**Comment by pbelgundi** [comment]
Volume Mounted Config Maps are updated automatically.
From K8s documentation:
```
Mounted ConfigMaps are updated automatically
When a ConfigMap already being consumed in a volume is updated, projected keys are eventually updated as well. Kubelet is checking whether the mounted ConfigMap is fresh on every periodic sync. However, it is using its local ttl-based cache for getting the current value of the ConfigMap. As a result, the total delay from the moment when the ConfigMap is updated to the moment when new keys are projected to the pod can be as long as kubelet sync period + ttl of ConfigMaps cache in kubelet.
``` 
However, in our case the problem is that zk directly tries to update the config files instead of updating the config map.
