### ISSUE TITLE
Should support and default to zookeeper official image

### ISSUE THREAD

**Issue by donbowman** [pravega/zookeeper-operator#74]
3.5 zookeeper has an `official` image on Dockerhub [here](https://hub.docker.com/_/zookeeper).

the emccorp one its not clear its maintained, the latest is 6 mo old and is pre-release.

should switch to default to the _official_ image.

this also means changing the `command`

**Comment by spiegela** [comment]
Actually the Docker container file for `emccorp/zookeeper` is included within this repo. We should bump it to the 3.5 final, but it is required as it has several scripts used for custom startup, readiness and liveness checks.

**Comment by donbowman** [comment]
i would recommend mounting the scripts u need as configmaps, then u can use the upstream directly.
this is how i did the helm change.
https://github.com/helm/charts/pull/11343

**Comment by abh** [comment]
Putting scripts in configmaps sounds ... not great.  Liveness and readiness checks might be able to fit in a sidecar (not the custom startup scripts though, most likely).

Maybe the official images will take patches to support the things we need here?

**Comment by spiegela** [comment]
Another option would be to add an initContainer that populates the `/data` volume with the required scripts and the `zu` utility.  @EronWright Do you have an opinion on this?

**Comment by EronWright** [comment]
From an OSS perspective, it does seem good to use the stock image.   I don't know enough about the scripts to have a strong opinion.   The sidecar pattern is highly useful for liveness checks, as mentioned above.  I would strive for that if possible.

**Comment by AceHack** [comment]
We would like to see this, any new thoughts on using this?

**Comment by fpj** [comment]
Note that the "official" image is not an image produced by the Apache community, see for example the "where to file issues" line:

 https://github.com/31z4/zookeeper-docker/issues

**Comment by fpj** [comment]
We are also not pushing images to `emccorp` on docker hub, we are pushing them under `pravega`:

https://hub.docker.com/repository/docker/pravega/zookeeper-operator

Is this issue still valid?

**Comment by anishakj** [comment]
Closing this issue as it is invalid.
