### ISSUE TITLE
allow to set a SeviceAccount to cluster Statefulset

### ISSUE THREAD

**Issue by prune998** [pravega/zookeeper-operator#78]
We need to be able to define a Kubernetes `ServiceAccount` in the Statefulset, so we can use images from private repositories (with specific ImagePullSecrets).

**Comment by pbelgundi** [comment]
@prune998 Could you please explain what you mean by "_define a Kubernetes ServiceAccount in the Statefulset_"
We do have a specific service account being created for the zk-operator in the chart:
https://github.com/pravega/zookeeper-operator/blob/master/charts/zookeeper-operator/values.yaml#L15

**Comment by prune998** [comment]
I mean, not in the chart of the Operator but in the Zookeeper Statefulset that is created by the Operator.
