### ISSUE TITLE
Can we use this operator to deploy zookeeper nodes across multiple clusters and multi-data center

### ISSUE THREAD

**Issue by praseedasathaye** [pravega/zookeeper-operator#90]
Basically is this using  reconfig API is being used when zk nodes come up/goes down across cluster/data-center?

**Comment by praseedasathaye** [comment]
Any information on this?

**Comment by leonj1** [comment]
K8s operators work on single clusters, not multiple. I doubt this will help you.

**Comment by pbelgundi** [comment]
@praseedasathaye This zookeeper operator can be used to deploy and manage multiple zookeeper clusters across namespaces.

**Comment by anishakj** [comment]
Closing this issue,  as the query is answered.
